# whole set

In [9]:
import pandas as pd
pd.set_option('display.max_columns', None)
lang = "Chinese"


df = pd.read_csv(f"annotation_whole_{lang.lower()}.csv")

cols = []
for i in range(1, 6):
    cols.append(f"Input.English{i}")
    cols.append(f"Input.{lang}{i}")
    cols.append(f"Answer.translation{i}")

df = df[['Title', 'Description', 'Keywords', 'WorkerId'] + cols]
df.columns

Index(['Title', 'Description', 'Keywords', 'WorkerId', 'Input.English1',
       'Input.Chinese1', 'Answer.translation1', 'Input.English2',
       'Input.Chinese2', 'Answer.translation2', 'Input.English3',
       'Input.Chinese3', 'Answer.translation3', 'Input.English4',
       'Input.Chinese4', 'Answer.translation4', 'Input.English5',
       'Input.Chinese5', 'Answer.translation5'],
      dtype='object')

In [10]:
df.head(50)

,Title,Description,Keywords,WorkerId,Input.English1,Input.Chinese1,Answer.translation1,Input.English2,Input.Chinese2,Answer.translation2,Input.English3,Input.Chinese3,Answer.translation3,Input.English4,Input.Chinese4,Answer.translation4,Input.English5,Input.Chinese5,Answer.translation5
0,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,reproducing property,再现性质,复制性质,reprojection,重投影,重新投影,reprojection error,重投影误差,重新投影误差,reranker,重排序器 (reranker),重新排序器,reranking model,重排序模型,重新排序模型
1,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2QEE46N7PM4TZ,word sense disambiguation,词义消歧,词义消歧,word similarity,词语相似度,词语相似性,word surprisal,词惊喜值,词语惊讶度,word token,词标记,词元,word vector,词向量,词向量
2,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,word sense disambiguation,词义消歧,词义消歧,word similarity,词语相似度,词语相似度,word surprisal,词惊喜值,词语惊讶度,word token,词标记,词语标记,word vector,词向量,词向量
3,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A8GUBFG0IW2E1,word sense disambiguation,词义消歧,词义消歧,word similarity,词语相似度,词语相似度,word surprisal,词惊喜值,词语意外度,word token,词标记,词符,word vector,词向量,词向量
4,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3GRZ06RPLS7YO,word sense disambiguation,词义消歧,词义消歧,word similarity,词语相似度,词语相似性,word surprisal,词惊喜值,词语意外性,word token,词标记,词语标记,word vector,词向量,词向量
5,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2RFY9YXUWY2E1,word sense disambiguation,词义消歧,词义消歧,word similarity,词语相似度,词语相似度,word surprisal,词惊喜值,词语意外度,word token,词标记,词符,word vector,词向量,词向量
6,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2A5EJSJ1F1ZBP,word sense disambiguation,词义消歧,الترجمة (بالعربية): كاشف كاني,word similarity,词语相似度,الترجمة (بالعربية): كاشف كاني,word surprisal,词惊喜值,الترجمة (بالعربية): كاشف كاني,word token,词标记,الترجمة (بالعربية): كاشف كاني,word vector,词向量,الترجمة (بالعربية): كاشف كاني
7,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1Q69IJIVE9AL3,word vector representation,词向量表示,词向量表示,word-aligned corpus,词对齐语料库,词对齐语料库,word-level,单词级别,词级/词层级,word-level vocabulary,词级词汇表,词级词汇表,word2vec,word2vec,词向量模型（word2vec）
8,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2RFY9YXUWY2E1,word vector representation,词向量表示,词向量表示,word-aligned corpus,词对齐语料库,词对齐语料库,word-level,单词级别,词级,word-level vocabulary,词级词汇表,词级词汇表,word2vec,word2vec,word2vec
9,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2QEE46N7PM4TZ,word vector representation,词向量表示,词向量表示,word-aligned corpus,词对齐语料库,词对齐语料库,word-level,单词级别,词级,word-level vocabulary,词级词汇表,词汇表（词级）,word2vec,word2vec,word2vec
10,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2E8AEWMZZY1DD,word vector representation,词向量表示,单词向量表示,word-aligned corpus,词对齐语料库,单词对齐语料库,word-level,单词级别,单词级别,word-level vocabulary,词级词汇表,单词级词汇表,word2vec,word2vec,word2vec
11,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,word vector representation,词向量表示,词向量表示,word-aligned corpus,词对齐语料库,词对齐语料库,word-level,单词级别,词级别,word-level vocabulary,词级词汇表,词级词汇,word2vec,word2vec,具体含义需根据上下文确定
12,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A8GUBFG0IW2E1,word vector representation,词向量表示,独热表示,word-aligned corpus,词对齐语料库,独热向量,word-level,单词级别,单样本学习,word-level vocabulary,词级词汇表,单样本设置,word2vec,word2vec,单阶段检测器
13,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2A5EJSJ1F1ZBP,word vector representation,词向量表示,الترجمة (بالعربية): كاشف كاني,word-aligned corpus,词对齐语料库,الترجمة (بالعربية): كاشف كاني,word-level,单词级别,الترجمة (بالعربية): كاشف كاني,word-level vocabulary,词级词汇表,الترجمة (بالعربية): كاشف كاني,word2vec,word2vec,الترجمة (بالعربية): كاشف كاني
14,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,reranking parser,重排序分析器,重新排序解析器,research,研究,研究,reservoir sampling,蓄水池采样,水库采样,residual block,残差块,残差块,residual branch,残差分支,残差分支
15,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1Q69IJIVE9AL3,word2vec embedding,词向量嵌入,word2vec 嵌入,words,字,词汇,world state,世界状态,世界状态,worst case,最坏情况,最坏情况,worst-case regret,最坏情况遗憾,最坏情况遗憾
16,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A8GUBFG0IW2E1,word2vec embedding,词向量嵌入,word2vec词嵌入,words,字,词语,world state,世界状态,世界状态,worst case,最坏情况,最坏情况,worst-case regret,最坏情况遗憾,最坏情况遗憾
17,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3GRZ06RPLS7YO,word2vec embedding,词向量嵌入,word2vec 嵌入,words,字,词汇,world state,世界状态,世界状态,worst case,最坏情况,最坏情况,worst-case regret,最坏情况遗憾,最坏情况后悔
18,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",AI0E8NNAL3MRQ,written,书面,书面的,zero-one loss,0-1损失,零一损失,zero-shot classification,零样本分类,零样本分类,zero-shot cross-lingual setting,零样本跨语言设置,零样本跨语言设置,zero-shot generalization,零样本泛化,零样本泛化
19,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A336SDY652S9GU,written,书面,书面的,zero-one loss,0-1损失,0-1损失,zero-shot classification,零样本分类,零样本分类,zero-shot cross-lingual setting,零样本跨语言设置,零样本跨语言设置,zero-shot generalization,零样本泛化,零样本泛化
20,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1Q69IJIVE9AL3,written,书面,书面,zero-one loss,0-1损失,零一损失,zero-shot classification,零样本分类,零样本分类,zero-shot cross-lingual setting,零样本跨语言设置,零样本跨语言设置,zero-shot generalization,零样本泛化,零样本泛化
21,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2A5EJSJ1F1ZBP,written,书面,分类标记,zero-one loss,0-1损失,分类标记,zero-shot classification,零样本分类,分类标记,zero-shot cross-lingual setting,零样本跨语言设置,分类标记,zero-shot generalization,零样本泛化,分类标记 分类标记
22,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3GRZ06RPLS7YO,written,书面,书面,zero-one loss,0-1损失,零一损失,zero-shot classification,零样本分类,零样本分类,zero-shot cross-lingual setting,零样本跨语言设置,零样本跨语言设置,zero-shot generalization,零样本泛化,零样本泛化
23,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A8GUBFG0IW2E1,residual network,残差网络,残差网络,resources,资源,资源,restricted isometry property,限制等距性质,受限等距性质,retrieval,检索,检索,retrieval,恢复,检索
24,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A336SDY652S9GU,zero-shot learning,零样本学习,中文翻译: 零样本学习,zero-shot prediction,零样本预测,中文翻译: 零样本预测,zero-shot prompting,零样本提示,中文翻译: 零样本提示,zero-shot reasoning,零样本推理,中文翻译: 零样本推理,zero-shot setting,零样本设置,中文翻译: 零样本设置
25,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",AXPTF739HYEZX,zero-shot learning,零样本学习,零样本学习,zero-shot prediction,零样本预测,零样本预测,zero-shot prompting,零样本提示,零样本提示,zero-shot reasoning,零样本推理,零样本推理,zero-shot setting,零样本设置,零样本设置
26,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A8GUBFG0IW2E1,zero-shot learning,零样本学习,零样本学习,zero-shot prediction,零样本预测,零样本预测,zero-shot prompting,零样本提示,零样本提示,zero-shot reasoning,零样本推理,零样本推理,zero-shot setting,零样本设置,零样本设置
27,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2RFY9YXUWY2E1,zero-shot learning,零样本学习,零样本学习,zero-shot prediction,零样本预测,零样本预测,zero-shot prompting,零样本提示,零样本提示,zero-shot reasoning,零样本推理,零样本推理,zero-shot setting,零样本设置,零样本设置
28,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,retrieval function,检索函数,检索函数,retrieval method,检索方法,检索方法,retrieval model,检索模型,检索模型,retrieval system,检索系统,检索系统,retrieved,检索到,检索到的
29,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A8GUBFG0IW2E1,retrieval function,检索函数,检索函数,retrieval method,检索方法,检索方法,retrieval model,检索模型,检索模型,retrieval system,检索系统,检索系统,retrieved,检索到,检索到的
30,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1Q69IJIVE9AL3,zero-shot transfer,零次迁移,零样本迁移,zero-shot transfer learning,零样本迁移学习,零样本迁移学习,NaN,NaN,no source terminologies or context paragraphs ...,NaN,NaN,no source terminologies or context paragraphs ...,NaN,NaN,no source terminologies or context paragraphs ...
31,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2RFY9YXUWY2E1,zero-shot transfer,零次迁移,零样本迁移,zero-shot transfer learning,零样本迁移学习,零样本迁移学习,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A8GUBFG0IW2E1,zero-shot transfer,零次迁移,零样本迁移,zero-shot transfer learning,零样本迁移学习,零样本迁移学习,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,zero-shot transfer,零次迁移,零样本迁移,zero-shot transfer learning,零样本迁移学习,零样本迁移学习,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,reverse-mode,逆向模式,反向模式,reward,奖励,奖励,reward model,奖励模型,奖励模型,reward shaping,奖励塑形,奖励塑造,reward signal,奖赏信号,奖励信号
35,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1XTTWEHGSK356,equivariant,等变,等变的,error,误差,错误,error analysis,错误分析,错误分析,error bound,误差界限,错误界,error function,误差函数,误差函数
36,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",AI0E8NNAL3MRQ,equivariant,等变,等变的,error,误差,误差,error analysis,错误分析,误差分析,error bound,误差界限,误差界,error function,误差函数,误差函数
37,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2E8AEWMZZY1DD,equivariant,等变,等变的,error,误差,误差,error analysis,错误分析,误差分析,error bound,误差界限,误差界限,error function,误差函数,误差函数
38,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2QEE46N7PM4TZ,equivariant,等变,等变的,error,误差,误差,error analysis,错误分析,误差分析,error bound,误差界限,误差界限,error function,误差函数,误差函数
39,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3GRZ06RPLS7YO,equivariant,等变,等变的,error,误差,误差,error analysis,错误分析,误差分析,error bound,误差界限,误差界限,error function,误差函数,误差函数
40,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,equivariant,等变,等变的,error,误差,误差,error analysis,错误分析,误差分析,error bound,误差界限,误差界,error function,误差函数,误差函数
41,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2A5EJSJ1F1ZBP,equivariant,等变,维物体检测,error,误差,维物体检测,error analysis,错误分析,维物体检测,error bound,误差界限,维物体检测,error function,误差函数,维物体检测
42,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2RFY9YXUWY2E1,equivariant,等变,等变的,error,误差,误差,error analysis,错误分析,误差分析,error bound,误差界限,误差界,error function,误差函数,误差函数
43,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1K8ASQMSHKL4F,10-fold cross validation,十折交叉验证,10折交叉验证,1D convolution,1D 卷积,一维卷积,2 norm,2范数,二范数,2D convolution,二维卷积,二维卷积,2D image,二维图像,二维图像
44,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3FQAQG99KBI9A,10-fold cross validation,十折交叉验证,10折交叉验证,1D convolution,1D 卷积,一维卷积,2 norm,2范数,2范数,2D convolution,二维卷积,二维卷积,2D image,二维图像,二维图像
45,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3ND1PA3UG9DXF,10-fold cross validation,十折交叉验证,10折交叉验证,1D convolution,1D 卷积,一维卷积,2 norm,2范数,二范数,2D convolution,二维卷积,二维卷积,2D image,二维图像,二维图像
46,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2A5EJSJ1F1ZBP,10-fold cross validation,十折交叉验证,الترجمة (بالعربية): كاشف كاني,1D convolution,1D 卷积,الترجمة (بالعربية): كاشف كاني,2 norm,2范数,الترجمة (بالعربية): كاشف كاني,2D convolution,二维卷积,الترجمة (بالعربية): كاشف كاني,2D image,二维图像,الترجمة (بالعربية): كاشف كاني
47,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2RFY9YXUWY2E1,10-fold cross validation,十折交叉验证,10折交叉验证,1D convolution,1D 卷积,一维卷积,2 norm,2范数,2范数,2D convolution,二维卷积,二维卷积,2D image,二维图像,二维图像
48,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A336SDY652S9GU,average loss,平均损失,平均损失,averaged perceptron,平均感知器,平均感知器,averaged perceptron algorithm,平均感知机算法,平均感知器算法,axis-aligned rectangle,轴对齐矩形,轴对齐矩形,back-off strategy,回退策略,回退策略
49,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2QEE46N7PM4TZ,average loss,平均损失,平均损失,averaged perceptron,平均感知器,平均感知机,averaged perceptron algorithm,平均感知机算法,平均感知机算法,axis-aligned rectangle,轴对齐矩形,轴对齐矩形,back-off strategy,回退策略,回退策略

# test set

In [188]:
import pandas as pd
pd.set_option('display.max_columns', None)
lang = "Chinese"


df = pd.read_csv(f"testset_{lang.lower()}.csv")

cols = []
for i in range(1, 6):
    cols.append(f"Input.English_{i}")
    cols.append(f"Input.{lang}_{i}")
    cols.append(f"Answer.translation{i}")

df = df[['Title', 'Description', 'Keywords', 'WorkerId'] + cols]
df.columns

Index(['Title', 'Description', 'Keywords', 'WorkerId', 'Input.English_1',
       'Input.Chinese_1', 'Answer.translation1', 'Input.English_2',
       'Input.Chinese_2', 'Answer.translation2', 'Input.English_3',
       'Input.Chinese_3', 'Answer.translation3', 'Input.English_4',
       'Input.Chinese_4', 'Answer.translation4', 'Input.English_5',
       'Input.Chinese_5', 'Answer.translation5'],
      dtype='object')

In [187]:
pd.set_option('display.max_rows', None)
df['WorkerId'].value_counts().shape

(90,)

In [144]:
df['WorkerId'].value_counts()

WorkerId
A2UX5ABV1UT5U1    5
A155OW7UP21THF    5
ABZDE9DEZ52P9     5
A2AWPIO9IMZO9P    5
A16LZF91UIO84J    4
A75XMBFY3UB9C     4
A2CQSBUU0FQ0PM    4
ANSNFANEJY1SZ     4
AZVPAN79C4CY8     4
A1OLMQU6NU65OM    4
A2EWL3H4XVVGC1    3
A3MEWZK69LTDJZ    3
AXPC0WQ9DAK4I     3
A385PM8TKY4SBN    3
A3LU3D1LHPLW6Z    3
A3EBN8D8YBZ205    3
AHSXZV2TRQKCU     3
A33S3NQJEHPOMN    3
A5SGZNLQXKSB5     3
A1J8KINFE2DWTR    3
A5LL8EKITZLQ0     2
A1YA58RRBN7NI4    2
A1E34A92PSX82M    2
A14L5O2IAVTSHD    2
A9Q02UNHS6TR1     2
A3JGCW0MKTFPYE    2
A38DSDPZGUO77O    2
A3G58G62R7YBAE    2
A24I2NW1ZVY76S    2
A310X45W0O0G8F    2
A32V9WY8YRCAP8    2
A3KNIP0TZFD4WT    2
AB2ASFW9CSRX4     2
A3A6RGC6U41CM5    2
A3V6NQ85ZZOE0G    1
A1NKR0W7QUA0CW    1
A1WU6EAI7ZUTD8    1
A3BKGBPR9TDO5     1
A2ZGM0NVVCXMUN    1
A10S4773ZBOEUU    1
A1V41YMR4AKA4G    1
A39NCWTB8S9SVH    1
A1FSDLJXNLOK3D    1
AHFIYVWSXHAVK     1
A1OWM3QO7QAKBN    1
A14F5XX4Y4KG9P    1
A2ZM8G6EGJORH3    1
AMIH1U8FA0VTC     1
A137D1IABG8R0Z    1
A34WFYXGEJ3EBC    1
A1HU37WA7MHN57    1
A6WYLP6W5TDOZ     1
A2BK919J29TOEE    1
A1KBUTIT38CPYY    1
A324P6L6O95TWM    1
AOGUVIIJIXYO3     1
AR5N626U38LPA     1
A1WPT6LLCRWMDY    1
AATNSR9QAYC5Q     1
A3JCU9GCZ8FP97    1
A3DIAIOB1DURSN    1
A1OL8K768KSY6L    1
A2QI7OJGJ94BX5    1
A1KRZO8X16T93E    1
ALX1395H43FUL     1
A2I68BIV4JQT2     1
A2EI5SEWZ699W8    1
A3HDXVNO786Z0L    1
A36CA3E5LT6I1P    1
A2OTFVI83FT0QL    1
ARHMCHIBGJ4FS     1
A2NMAOYBBJTO0R    1
AR5QAOVQR0OWN     1
AMDP4QV7L82Q      1
A15VQD1AZ0M6XO    1
A3ND1PA3UG9DXF    1
A2N456126P6KQU    1
A1PMUCO3BK6C26    1
A8GUBFG0IW2E1     1
A2A5EJSJ1F1ZBP    1
A71PDDT7XY0YV     1
A2DXSNQM308NHW    1
Name: count, dtype: int64

In [168]:
df['Input.English_1'].value_counts()

Input.English_1
constituency parser      30
text mining              30
word alignment           30
convolutional network    30
attention model          30
Name: count, dtype: int64

In [189]:
# chinese
qualified = []
unqualified = ['A3V6NQ85ZZOE0G', 'A36L0Y4GIPC4RT', 'A27I49E3ZGOXPD', 'A1NZZBNAVXCSTS',
 'A1S9SJ5CZTZH1M',
 'A1HU37WA7MHN57',
 'A7F86G1M4A22D',
 'A1PMUCO3BK6C26',
 'A2NMAOYBBJTO0R',
 'A2OHI6FWDK10B2',
 'A1L80XZNXJK57Q',
 'AXTFETMDXEH8E',
 'A1GWX6EL2FV71N',
 'A1WQHQM1TLNU0P',
 'A205UJLRQXJ3LQ',
 'A2I4Y9OC10S8Q4',
 'A3GRZ06RPLS7YO',
 'A3NNEMD2T3YXJO',
 'A2EI5SEWZ699W8',
 'A2C6F3MV97A2YF',
 'AEIDL4NYQG5N0', 'A89MOSYM3Z7NU', 'AEQX4D8XEB8AC', 'AH2ZAM7R9RZYJ', 'A3TUTQYBMO8EVE', 'A2B95TZ8CXMCZ2']

In [162]:
# arabic
qualified = []
unqualified = ['A16LZF91UIO84J', 'AHFIYVWSXHAVK', 'AB2ASFW9CSRX4', 'A34WFYXGEJ3EBC', 'AR5N626U38LPA',
 'A75XMBFY3UB9C',
 'A1J8KINFE2DWTR',
 'A310X45W0O0G8F',
 'A2UX5ABV1UT5U1',
 'A385PM8TKY4SBN',
 'ANSNFANEJY1SZ',
 'A3KNIP0TZFD4WT',
 'A32V9WY8YRCAP8',
 'A1OWM3QO7QAKBN',
 'A1OLMQU6NU65OM',
 'A14F5XX4Y4KG9P',
 'A2ZM8G6EGJORH3',
 'A2AWPIO9IMZO9P',
 'A1HU37WA7MHN57',
 'A5SGZNLQXKSB5',
 'ABZDE9DEZ52P9',
 'A9Q02UNHS6TR1',
 'AATNSR9QAYC5Q',
 'A3JCU9GCZ8FP97',
 'AHSXZV2TRQKCU',
 'A2QI7OJGJ94BX5',
 'A3JGCW0MKTFPYE',
 'A2I68BIV4JQT2',
 'ARHMCHIBGJ4FS',
 'A2CQSBUU0FQ0PM','AOGUVIIJIXYO3']

In [137]:
# japanese
unqualified = ['A1SB9YPRBEOQZB',
 'A3V6NQ85ZZOE0G',
 'A3UJE47H1K50LC',
 'AAC5O38A5M1S2',
 'AGTKN7I63HWHK',
 'A1K8ASQMSHKL4F',
 'A3DGD7QAB0WPJX',
 'A249YEMF3IOF8F',
 'A4D99Y82KOLC8',
 'ARHMCHIBGJ4FS',
 'A39FDFI098JTP5',
 'AXXQB17L7J3YH',
 'AGWVZMETSUCX3',
 'A26AH6DPNIH2FQ',
 'A11EI3B3JERT54',
 'A3OUUI8MXMBUTA',
 'A2NMAOYBBJTO0R',
 'A2R8TEJS54TWTU',
 'AXS36Z8214JTS',
 'AOGUVIIJIXYO3',
 'AHFIYVWSXHAVK',
 'A33J90UPYHY7WJ',
 'A7F8W5J23JOTW',
 'AZBP3WE6X2VQV',
 'A1R8VFS8YKJS4Y',
 'AU89IGLQ6AD15', 'A146KBI8D4W4WG', 'A1RAJW5O9HPPE2', 'A14F5XX4Y4KG9P', 'A2I68BIV4JQT2', 'A334XBMTC9R27G', 'A14ZPKPAPASF9U', 'A4PMJXTA7ARKK', 'A34I1UGKSNQR19', 'A1B2BTCGBB6IAM', 'A1IVT8140ZLTPC', 'A2AKGCCDHISUL2', 'A33C0IP40ZZPKS', 'A1X1DXK737Y6BX']

In [119]:
# russian
qualified = []
unqualified = ['A124QC05SSRJC3', 'A14ZPKPAPASF9U', 'AAC5O38A5M1S2', 'A3V6NQ85ZZOE0G', 'AD0XVQHIIJ3RP', 'A2OHI6FWDK10B2', 'AH2ZAM7R9RZYJ', 'A3D07A2MNDBKXK', 'AV06F0ZLGC1IN', 'A1K8ASQMSHKL4F', 'A30HJVRR2UWFKT', 'A2P2UPJBOGP2X3', 'AR5QAOVQR0OWN', 'A3EJ5A0GPHKO9J', 'A38SEBVG1J8TH7', 'A3KPN42GS526BV', 'AJIBKYHREAFYX', 'A23A5MAUY0PF30', 'A3EAM8CRMJ51KX', 'A5LIMBZCZR3FD', 'AW9EDTAGKNC57', 'A1BMCLI45I47Z3', 'A3ORTMILSRG4HL', 'AGTKN7I63HWHK', 'A2FWE58QKZAUVL', 'A2B9IE51SDRIDV']

In [185]:
df.loc[(df['Input.English_1'] == "attention model") & (~df['WorkerId'].isin(unqualified))]

,Title,Description,Keywords,WorkerId,Input.English_1,Input.Chinese_1,Answer.translation1,Input.English_2,Input.Chinese_2,Answer.translation2,Input.English_3,Input.Chinese_3,Answer.translation3,Input.English_4,Input.Chinese_4,Answer.translation4,Input.English_5,Input.Chinese_5,Answer.translation5
120,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1XFP99524J1AH,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力分数
121,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2VNIOI5GX51C6,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
122,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A18BYZ5AOGG4PZ,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
125,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1RAJW5O9HPPE2,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
127,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2P2UPJBOGP2X3,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
128,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2QI7OJGJ94BX5,attention model,注意力模型,卷积网络,attention module,注意力模块,卷积神经网络,attention operation,注意力运算,卷积神经网络,attention pattern,注意力模式,卷积表示,attention score,注意力分数,冷却计划
129,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1XTTWEHGSK356,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力分数
130,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1OSAIXJPUXJFO,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
131,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A336SDY652S9GU,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力运算,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
132,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A18YWTRM269A46,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
133,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A18CB87XJS64Z0,attention model,注意力模型,注意力机制,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
134,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",AXPTF739HYEZX,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
136,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3AO3IL9E9N3KG,attention model,注意力模型,注意模型,attention module,注意力模块,注意模块,attention operation,注意力运算,注意操作,attention pattern,注意力模式,注意模式,attention score,注意力分数,注意分数
137,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A291EAOGL08IFT,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
138,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A4TT6QM1DNVDW,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
139,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3TUTQYBMO8EVE,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
140,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2BHV2GVLH0E7F,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
141,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3EBN8D8YBZ205,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力分数
142,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3A6RGC6U41CM5,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力分数
143,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A39XTLND9LZCIE,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力得分
145,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2RFY9YXUWY2E1,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力分数
146,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2ZN3Q6015GOUA,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力分数
147,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A11TLWECSEYVCV,attention model,注意力模型,注意力模型,attention module,注意力模块,注意力模块,attention operation,注意力运算,注意力操作,attention pattern,注意力模式,注意力模式,attention score,注意力分数,注意力分数
149,Rate the quality of a translation Test (Chines...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2B95TZ8CXMCZ2,attention model,注意力模型,1: 对这些表情动作单元（AUs）进行条件化GAN模型训练，使生成器通过简单的插值渲染出各种...,attention module,注意力模块,1: 然而，我们进行了一些重要的修改：注意力模块选择一个 5 × 5 的值 V 区块，围绕当...,attention operation,注意力运算,1: 然而，我们进行了一些重要的修改：注意力模块选择一个 5 × 5 的值 V 区块，围绕当...,attention pattern,注意力模式,"尽管一些研究（Ramsauer et al., 2021）已经努力深入理解注意力，但普遍的直...",attention score,注意力分数,1: 其中 L(x) 是示例 x 的损失函数，A h 是第 h 个头的注意力得分，如公式 (...

In [190]:
list(set(df['WorkerId'].unique().tolist()).difference(set(unqualified)))

['A3DIAIOB1DURSN',
 'A2KVEENUGDUVCA',
 'AATGWVVPQJSIT',
 'A1RAJW5O9HPPE2',
 'A3BAG557BXSRF6',
 'A1F8RTA04QKNFY',
 'A2BK919J29TOEE',
 'A2ZN3Q6015GOUA',
 'A27IWP9QQQBX44',
 'A2P2UPJBOGP2X3',
 'A18CB87XJS64Z0',
 'A15VQD1AZ0M6XO',
 'A1GMWF04URJMID',
 'A39FMG8IFNI7ZH',
 'A1K8ASQMSHKL4F',
 'A2RFY9YXUWY2E1',
 'A2A5EJSJ1F1ZBP',
 'A3ND1PA3UG9DXF',
 'A1WU6EAI7ZUTD8',
 'A336SDY652S9GU',
 'A24Z95OIWVVVG5',
 'A4TT6QM1DNVDW',
 'A18BYZ5AOGG4PZ',
 'A1XFP99524J1AH',
 'A3AO3IL9E9N3KG',
 'A2BHV2GVLH0E7F',
 'A18YWTRM269A46',
 'A2QI7OJGJ94BX5',
 'A1OSAIXJPUXJFO',
 'A3EBN8D8YBZ205',
 'A39NCWTB8S9SVH',
 'A2IU5W5ZRWT2IJ',
 'A3KNIP0TZFD4WT',
 'AR9SXKQ8Q7HLG',
 'A3BM1VCX0Q3UYD',
 'A25HETTI76GHCL',
 'A291EAOGL08IFT',
 'A29317JWUEQHQS',
 'AWK89QECL03SP',
 'A11TLWECSEYVCV',
 'A39XTLND9LZCIE',
 'A36CA3E5LT6I1P',
 'A1NCJ9ZW5VRLQI',
 'AXPTF739HYEZX',
 'A2VNIOI5GX51C6',
 'AQHKPPYJJBSI9',
 'A1XTTWEHGSK356',
 'A1NT1TU7ZPA5TF',
 'A1OEV14LXA0N3Y',
 'A3A6RGC6U41CM5',
 'A3VS380YGMLLXY',
 'A14PUCZ4085DCC',
 'A150AEWMJM2G8O',
 'AI0E8NNAL3MRQ',
 'A1Q7ADXOEB8VTY',
 'A3EHOXHLQ2JGSW']

In [39]:
df.loc[(df['Input.English_1'] == 'attention model') & (~df['WorkerId'].isin(unqualified))]

,Title,Description,Keywords,WorkerId,Input.English_1,Input.Japanese_1,Answer.translation1,Input.English_2,Input.Japanese_2,Answer.translation2,Input.English_3,Input.Japanese_3,Answer.translation3,Input.English_4,Input.Japanese_4,Answer.translation4,Input.English_5,Input.Japanese_5,Answer.translation5
120,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A201U6OACI4229,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
121,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2M8BZNDMJ81YD,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
123,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A4D99Y82KOLC8,attention model,注意モデル,Chūmoku moderu,attention module,注意モジュール,Chūi mojūru,attention operation,注意操作,Chūi sōsa,attention pattern,アテンションパターン,Chūi patān,attention score,注意スコア,Chūi sukoa
124,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3593QQMEY5RQZ,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
126,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3BAG557BXSRF6,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション操作,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア
127,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1HHF3CTTUY6W1,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
128,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2AKGCCDHISUL2,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション操作,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア
129,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",AMIH1U8FA0VTC,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
130,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1IVT8140ZLTPC,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
131,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1X1DXK737Y6BX,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
132,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A10S4773ZBOEUU,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション操作,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア
133,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2FPGD8LHBTJJJ,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション・オペレーション,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア
134,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",AXXQB17L7J3YH,attention model,注意モデル,注意モデル (または 注意機構),attention module,注意モジュール,注意モジュール (または 注意機能),attention operation,注意操作,注意操作 (または 注意処理),attention pattern,アテンションパターン,注意パターン (または 注意のパターン),attention score,注意スコア,注意スコア (または 注意点数)
135,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3EBN8D8YBZ205,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
136,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A33J90UPYHY7WJ,attention model,注意モデル,注意機構モデル This refers to a type of model in mach...,attention module,注意モジュール,注意モジュール This refers to a component or part of ...,attention operation,注意操作,注意操作 This refers to the specific process or fu...,attention pattern,アテンションパターン,注意パターン (ちゅういパターン) This refers to the specific...,attention score,注意スコア,注意スコア (ちゅういスコア) This refers to the numerical ...
137,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A39NCWTB8S9SVH,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション操作,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア
138,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A14ZPKPAPASF9U,attention model,注意モデル,注目モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
139,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1DEIZQB0X8KNT,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
140,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3A6RGC6U41CM5,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション操作,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア
141,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A150AEWMJM2G8O,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
142,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A23RUJ6HQOITB0,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
143,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3AIGHKZTTAPX1,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション操作,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア
145,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A2DXSNQM308NHW,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション操作,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア
147,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A324P6L6O95TWM,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
148,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1B2BTCGBB6IAM,attention model,注意モデル,注意モデル,attention module,注意モジュール,注意モジュール,attention operation,注意操作,注意操作,attention pattern,アテンションパターン,注意パターン,attention score,注意スコア,注意スコア
149,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A1Y735GLCKHM47,attention model,注意モデル,アテンションモデル,attention module,注意モジュール,アテンションモジュール,attention operation,注意操作,アテンション操作,attention pattern,アテンションパターン,アテンションパターン,attention score,注意スコア,アテンションスコア

In [10]:
worker_id = "A3V6NQ85ZZOE0G"
df.loc[df['WorkerId'] == worker_id]

,Title,Description,Keywords,WorkerId,Input.English_1,Input.Japanese_1,Answer.translation1,Input.English_2,Input.Japanese_2,Answer.translation2,Input.English_3,Input.Japanese_3,Answer.translation3,Input.English_4,Input.Japanese_4,Answer.translation4,Input.English_5,Input.Japanese_5,Answer.translation5
5,Rate the quality of a translation Test (Japane...,"In this task, you will be evaluating the quali...","Translation, Terminology, Multilingual, Rating",A3V6NQ85ZZOE0G,constituency parser,構成素パーサー,شبكة عصبية التفافية,constituency parsing,構成素解析,شبكة عصبية التفافية,constituency tree,構成要素木 (kousei youso ki),شبكة عصبية التفافية,constituent parsing,構成素解析,شبكة عصبية التفافية,constituent structure,構成構造,شبكة عصبية التفافية