In [1]:
import json
import pandas as pd
tgt_langs = [
    "Chinese",
    "Arabic",
    "French",
    "Japanese",
    "Russian",
]

In [3]:
# models = ['gpt4omini', 'nllb', 'seamless', 'aya', 'aya_old']
models = ['aya_old']
exp_dict = {"default": "_comet", "prompt": "_prompt_gpt4omini_comet", "replace": "_hard_replace_comet"}
dataframe_dict = {}
for model in models:
    for exp_name, exp_suffix in exp_dict.items():
        column_name = f"{exp_name}_{model}"
        dataframe_dict[column_name] = []
        
        data = json.load(open(f"/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/data_eval_6060/eval/gold_predictions_dev_{model}{exp_suffix}.json"))
        for lang in tgt_langs:
            dataframe_dict[column_name].append(data.get(f"{lang}_system_score", 0))  # Use `.get()` with default value `0` if lang not found

# Create the DataFrame
df = pd.DataFrame(dataframe_dict, index=tgt_langs)
df

          default_aya_old  prompt_aya_old  replace_aya_old
Chinese          0.851212        0.857018         0.854999
Arabic           0.840186        0.848318         0.837807
French           0.823977        0.833370         0.822476
Japanese         0.879199        0.884172         0.880092
Russian          0.819089        0.823093         0.796471

In [5]:
# models = ['gpt4omini', 'nllb', 'seamless', 'aya', 'aya_old']
models = ['aya_old']
exp_dict = {"default": "_comet", "prompt": "_prompt_gpt4omini_comet", "replace": "_hard_replace_comet"}
dataframe_dict = {}
for model in models:
    for exp_name, exp_suffix in exp_dict.items():
        column_name = f"{exp_name}_{model}"
        dataframe_dict[column_name] = []
        
        data = json.load(open(f"/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/{model}{exp_suffix}.json"))
        for lang in tgt_langs:
            dataframe_dict[column_name].append(data.get(f"{lang}_system_score", 0))  # Use `.get()` with default value `0` if lang not found

# Create the DataFrame
df = pd.DataFrame(dataframe_dict, index=tgt_langs)
df

          default_aya_old  prompt_aya_old  replace_aya_old
Chinese          0.838833        0.845681         0.839240
Arabic           0.815461        0.825801         0.809256
French           0.825459        0.837685         0.818420
Japanese         0.844207        0.852290         0.844394
Russian          0.827174        0.838537         0.806392

# V1

In [1]:
import json
import pandas as pd

In [ ]:
tgt_langs = [
    "Chinese",
    "Arabic",
    "French",
    "Japanese",
    "Russian",
]

In [3]:
# data_g = json.load(open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/eval/predictions_dev_googletrans_comet.json", 'r'))
data_g = json.load(open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/eval/predictions_dev_googletrans_comet_noref_xl.json", 'r'))
data_g.keys()

dict_keys(['Chinese_scores', 'Chinese_system_score', 'Arabic_scores', 'Arabic_system_score', 'French_scores', 'French_system_score', 'Japanese_scores', 'Japanese_system_score', 'Russian_scores', 'Russian_system_score'])

In [4]:
# data_s = json.load(open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/eval/predictions_dev_seamless_comet.json", 'r'))
data_s = json.load(open("/home/jiaruil5/multilingual/multilingual-model-card/src/data_eval_6060/eval/predictions_dev_seamless_comet_noref_xl.json", 'r'))
data_s.keys()

dict_keys(['Chinese_scores', 'Chinese_system_score', 'Arabic_scores', 'Arabic_system_score', 'French_scores', 'French_system_score', 'Japanese_scores', 'Japanese_system_score', 'Russian_scores', 'Russian_system_score'])

In [5]:
from collections import defaultdict
scores_dict = defaultdict(list)
for tgt_lang in tgt_langs:
    # print(f"{tgt_lang}_system_score", data[f"{tgt_lang}_system_score"])
    scores_dict[f"{tgt_lang}_system_score"].append(data_g[f"{tgt_lang}_system_score"])
    scores_dict[f"{tgt_lang}_system_score"].append(data_s[f"{tgt_lang}_system_score"])

In [11]:
# comet
scores_dict = dict(scores_dict)
df = pd.DataFrame(scores_dict)
df = df.T
df.columns = ['googletrans', 'seamless']
df

                       googletrans  seamless
Chinese_system_score      0.883238  0.838839
Arabic_system_score       0.875397  0.842705
French_system_score       0.847238  0.835571
Japanese_system_score     0.898531  0.850210
Russian_system_score      0.842348  0.819786

In [6]:
# comet_noref_xl
scores_dict = dict(scores_dict)
df = pd.DataFrame(scores_dict)
df = df.T
df.columns = ['googletrans', 'seamless']
df

                       googletrans  seamless
Chinese_system_score      0.697709  0.647375
Arabic_system_score       0.705548  0.675481
French_system_score       0.688482  0.673085
Japanese_system_score     0.756414  0.676290
Russian_system_score      0.706763  0.680274