In [1]:
import pandas as pd
from multilingualmc.evaluator.eval_on_6060_gold import get_mean_std_dict

In [2]:
# dataset_path = '/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/data_eval_6060/eval/gold_predictions_dev_'
dataset_path = '/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/'

df_list = []
for model in ['nllb', 'seamless', 'gpt4omini']:
    df1 = pd.read_csv(f"{dataset_path}{model}.csv")
    res_g = get_mean_std_dict(df1)
    df2 = pd.read_csv(f"{dataset_path}{model}_prompt_gpt4omini.csv")
    res_s = get_mean_std_dict(df2)
    df3 = pd.read_csv(f"{dataset_path}{model}_hard_replace.csv")
    res_h = get_mean_std_dict(df3)
    df_g = pd.DataFrame.from_dict(res_g, orient='index')
    df_g.columns = [f'default_{model}']
    df_s = pd.DataFrame.from_dict(res_s, orient='index')
    df_s.columns = [f'prompt_{model}']
    df_h = pd.DataFrame.from_dict(res_h, orient='index')
    df_h.columns = [f'replace_{model}']
    df_list.extend([df_g, df_s, df_h])
df = pd.concat(df_list, axis=1)
pd.set_option('display.max_rows', None)
df

,default_nllb,prompt_nllb,replace_nllb,default_seamless,prompt_seamless,replace_seamless,default_gpt4omini,prompt_gpt4omini,replace_gpt4omini
Chinese_bleu_score_mean,11.786008,12.568087,12.369176,14.577784,15.361060,14.729387,18.163403,18.613260,18.682253
Chinese_bleu_score_std,13.226627,14.575323,13.789006,16.253853,16.480512,16.209216,19.071599,19.372648,19.511394
Chinese_bleu_1gram_precision_mean,11.842334,12.645925,12.432794,14.663101,15.461359,14.817236,18.262754,18.717899,18.783355
Chinese_bleu_1gram_precision_std,13.267864,14.627285,13.832658,16.290439,16.537242,16.258878,19.195887,19.499995,19.637914
Chinese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_ref_len_mean,79.686000,80.482000,79.790000,78.620000,81.296000,78.620000,85.994000,85.944000,85.942000
Chinese_bleu_ref_len_std,33.948792,34.060798,33.957977,34.769029,35.315248,34.760152,37.015866,36.971647,36.929585
Chinese_bleu_pred_len_mean,83.708000,84.406000,83.806000,81.920000,84.510000,81.932000,89.454000,89.342000,89.398000
Chinese_bleu_pred_len_std,36.903584,36.813634,36.922173,36.974042,37.523672,36.974933,38.640316,38.555598,38.569558
Chinese_bleu_bp_mean,0.987602,0.988662,0.987520,0.990953,0.991059,0.991050,0.995720,0.995456,0.995746
Chinese_bleu_bp_std,0.090323,0.079188,0.090426,0.039519,0.036017,0.039447,0.020121,0.020501,0.020083
Chinese_bleu_ratio_mean,1.050481,1.048866,1.050350,1.041064,1.038912,1.041212,1.038656,1.038082,1.038607
Chinese_bleu_ratio_std,0.129467,0.121024,0.129176,0.074460,0.071187,0.074428,0.055139,0.055177,0.055043
Chinese_chrf_score_mean,12.428451,13.215857,13.042560,15.243478,16.035738,15.403386,18.872824,19.340585,19.391139
Chinese_chrf_score_std,13.615382,15.006597,14.232660,16.601074,16.787276,16.555399,19.388336,19.702731,19.803196
Chinese_ter_score_mean,99.364176,98.448421,98.398966,96.024740,94.855533,95.814434,91.394217,90.583412,90.485166
Chinese_ter_score_std,20.252611,21.174378,20.004216,22.616459,22.127501,22.566878,24.280140,24.061265,24.294907
Chinese_chrfpp_score_mean,12.428451,13.215857,13.042560,15.243478,16.035738,15.403386,18.872824,19.340585,19.391139
Chinese_chrfpp_score_std,13.615382,15.006597,14.232660,16.601074,16.787276,16.555399,19.388336,19.702731,19.803196
Arabic_bleu_score_mean,14.932141,15.308997,14.888841,15.413104,16.911392,16.047758,14.062891,15.055060,14.142294
Arabic_bleu_score_std,14.697143,16.187722,14.757673,15.729298,17.930474,16.551117,14.662603,15.549691,14.313356
Arabic_bleu_1gram_precision_mean,15.038609,15.400722,14.991907,15.518274,17.018048,16.153225,14.107944,15.101355,14.191256
Arabic_bleu_1gram_precision_std,14.749332,16.229465,14.798824,15.781303,17.998912,16.606244,14.672883,15.567331,14.329737
Arabic_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_ref_len_mean,176.040000,177.646000,176.498000,178.930000,179.450000,179.422000,180.446000,180.864000,180.960000
Arabic_bleu_ref_len_std,63.724281,64.020825,63.867834,63.564345,63.802830,63.888178,64.802359,64.899718,65.175748
Arabic_bleu_pred_len_mean,176.066000,177.678000,176.512000,178.862000,179.418000,179.332000,180.804000,181.272000,181.268000
Arabic_bleu_pred_len_std,63.865415,63.992064,63.992781,63.663058,63.828516,63.922719,64.906481,64.983719,65.300386
Arabic_bleu_bp_mean,0.990933,0.991928,0.990970,0.992356,0.993000,0.992469,0.995762,0.996187,0.995628
Arabic_bleu_bp_std,0.020699,0.020042,0.020676,0.011166,0.010198,0.010597,0.009209,0.008226,0.009204
Arabic_bleu_ratio_mean,0.999937,1.000251,0.999910,0.999621,1.000006,0.999694,1.001918,1.002253,1.001561
Arabic_bleu_ratio_std,0.033510,0.031770,0.033556,0.023386,0.022256,0.023168,0.015425,0.014618,0.015392
Arabic_chrf_score_mean,15.469924,15.835513,15.422767,15.932627,17.442127,16.580276,14.521218,15.528536,14.604094
Arabic_chrf_score_std,14.990845,16.485200,15.043534,15.977988,18.165288,16.783763,14.843226,15.740950,14.504279
Arabic_ter_score_mean,101.723658,101.265382,101.769189,101.165345,99.199076,100.313853,102.554782,101.174810,102.334003
Arabic_ter_score_std,18.618565,20.301376,18.661581,19.991202,22.233324,20.597205,18.452606,19.203576,17.899233
Arabic_chrfpp_score_mean,15.469924,15.835513,15.422767,15.932627,17.442127,16.580276,14.521218,15.528536,14.604094
Arabic_chrfpp_score_std,14.990845,16.485200,15.043534,15.977988,18.165288,16.783763,14.843226,15.740950,14.504279
French_bleu_score_mean,24.975488,25.117642,24.077608,26.406360,29.570654,25.919785,26.158622,27.965472,25.988394
French_bleu_score_std,22.897323,22.918604,22.312284,22.340410,24.270010,21.722066,23.872646,26.068474,23.395170
French_bleu_1gram_precision_mean,25.046143,25.175501,24.147517,26.474438,29.624366,25.989256,26.223490,28.024781,26.055236
French_bleu_1gram_precision_std,22.927936,22.950041,22.346020,22.374175,24.296072,21.767778,23.901148,26.095104,23.424056
French_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_ref_len_mean,206.090000,233.988000,206.656000,242.870000,246.706000,243.390000,251.474000,252.108000,251.660000
French_bleu_ref_len_std,84.978566,89.157917,85.027413,87.018421,87.524881,87.174725,91.174926,91.049989,91.243691
French_bleu_pred_len_mean,207.710000,235.634000,208.198000,244.390000,248.348000,244.850000,251.988000,252.676000,252.048000
French_bleu_pred_len_std,85.866828,89.639648,85.852992,87.788585,88.243349,87.847173,91.335690,91.199329,91.356103
French_bleu_bp_mean,0.996081,0.997156,0.996051,0.996016,0.996754,0.996094,0.996033,0.996471,0.995905
French_bleu_bp_std,0.012978,0.008456,0.012852,0.021401,0.021232,0.021302,0.021156,0.020921,0.021152
French_bleu_ratio_mean,1.008307,1.007946,1.008082,1.005270,1.005792,1.005202,1.001477,1.001681,1.001038
French_bleu_ratio_std,0.033046,0.028165,0.033442,0.025556,0.024477,0.025316,0.021849,0.021260,0.021763
French_chrf_score_mean,25.657747,25.796014,24.754195,27.126048,30.327410,26.641102,26.779602,28.570974,26.606184
French_chrf_score_std,23.095562,23.135070,22.529809,22.542258,24.452880,21.950765,24.021731,26.177565,23.554002
French_ter_score_mean,88.847077,88.663765,89.952903,87.042842,83.332483,87.519065,87.011173,84.845146,87.064146
French_ter_score_std,28.020712,27.799828,27.393444,27.203137,29.228578,26.260729,28.626814,30.988302,27.814036
French_chrfpp_score_mean,25.657747,25.796014,24.754195,27.126048,30.327410,26.641102,26.779602,28.570974,26.606184
French_chrfpp_score_std,23.095562,23.135070,22.529809,22.542258,24.452880,21.950765,24.021731,26.177565,23.554002
Japanese_bleu_score_mean,8.877999,9.498379,9.203868,9.433089,10.060445,9.840577,10.261729,10.674572,10.683256
Japanese_bleu_score_std,11.195843,12.210791,11.702536,11.701055,12.795067,12.559822,12.427501,12.789017,12.881927
Japanese_bleu_1gram_precision_mean,8.964482,9.574767,9.291412,9.477468,10.104279,9.884564,10.292917,10.709516,10.716678
Japanese_bleu_1gram_precision_std,11.341098,12.346076,11.851387,11.748187,12.838436,12.601980,12.522672,12.893805,12.978898
Japanese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_ref_len_mean,112.004000,112.920000,112.252000,112.002000,112.532000,112.070000,119.832000,119.404000,119.814000
Japanese_bleu_ref_len_std,44.160302,43.924530,44.225290,44.342785,43.719604,44.270949,44.923223,44.673664,44.969634
Japanese_bleu_pred_len_mean,115.970000,116.860000,116.252000,116.910000,117.280000,116.992000,124.938000,124.454000,124.898000
Japanese_bleu_pred_len_std,46.859457,46.452385,46.916723,46.744840,45.857556,46.636916,47.152145,46.843147,47.158620
Japanese_bleu_bp_mean,0.989911,0.991322,0.989997,0.992803,0.995131,0.992853,0.997058,0.996977,0.997007
Japanese_bleu_bp_std,0.057086,0.052148,0.056724,0.041459,0.025725,0.041463,0.019513,0.019552,0.019543
Japanese_bleu_ratio_mean,1.031891,1.032325,1.032180,1.042668,1.042441,1.042878,1.041394,1.041204,1.041341
Japanese_bleu_ratio_std,0.088077,0.084324,0.088013,0.076070,0.067920,0.076092,0.049356,0.049498,0.049355
Japanese_chrf_score_mean,9.271810,9.905175,9.618678,9.903314,10.535247,10.324864,10.703249,11.137465,11.139201
Japanese_chrf_score_std,11.524890,12.563030,12.035980,12.126059,13.214338,12.968852,12.702369,13.082895,13.179017
Japanese_ter_score_mean,100.637400,99.917637,100.443954,99.979292,99.090232,99.430065,98.778225,98.209088,98.141005
Japanese_ter_score_std,16.129959,16.919971,16.701540,16.831734,17.165030,17.085864,17.441214,17.269685,17.400999
Japanese_chrfpp_score_mean,9.271810,9.905175,9.618678,9.903314,10.535247,10.324864,10.703249,11.137465,11.139201
Japanese_chrfpp_score_std,11.524890,12.563030,12.035980,12.126059,13.214338,12.968852,12.702369,13.082895,13.179017
Russian_bleu_score_mean,18.859529,19.122750,18.871600,18.402493,19.592972,18.625881,18.889692,19.497648,18.708861
Russian_bleu_score_std,19.266427,19.576512,19.043098,17.667000,18.928593,17.560060,20.143794,20.774576,19.637522
Russian_bleu_1gram_precision_mean,18.918995,19.182352,18.933646,18.452873,19.649588,18.682497,18.971671,19.582059,18.794863
Russian_bleu_1gram_precision_std,19.275649,19.589518,19.055675,17.693548,18.960907,17.593193,20.180779,20.817093,19.678714
Russian_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_ref_len_mean,200.064000,220.336000,200.712000,228.910000,231.732000,229.346000,236.248000,235.944000,236.222000
Russian_bleu_ref_len_std,84.056164,85.083450,84.227535,82.187197,83.397064,82.218258,85.542138,85.436946,85.417006
Russian_bleu_pred_len_mean,201.290000,221.442000,201.930000,229.946000,232.762000,230.332000,236.258000,235.926000,236.158000
Russian_bleu_pred_len_std,85.186051,85.951859,85.319775,83.176004,84.393304,83.163418,85.966505,85.802194,85.771876
Russian_bleu_bp_mean,0.995498,0.995707,0.995520,0.995072,0.995092,0.994864,0.994558,0.994556,0.994396
Russian_bleu_bp_std,0.024599,0.024447,0.024594,0.025523,0.025554,0.025543,0.025522,0.025606,0.025535
Russian_bleu_ratio_mean,1.004637,1.003881,1.004743,1.002477,1.002515,1.002270,0.998384,0.998326,0.998122
Russian_bleu_ratio_std,0.029527,0.029496,0.030275,0.027505,0.027334,0.027555,0.024043,0.024064,0.024062
Russian_chrf_score_mean,19.332506,19.603675,19.365408,18.867215,20.074984,19.101722,19.299636,19.908209,19.117941
Russian_chrf_score_std,19.464846,19.781363,19.261181,17.833780,19.094084,17.729051,20.290879,20.912177,19.777378
Russian_ter_score_mean,93.793137,93.470535,93.718768,94.181978,92.716776,93.974547,93.397718,92.640630,93.567346
Russian_ter_score_std,23.418254,23.424508,22.839919,21.341938,22.347377,21.227191,23.978040,24.449049,23.448301
Russian_chrfpp_score_mean,19.332506,19.603675,19.365408,18.867215,20.074984,19.101722,19.299636,19.908209,19.117941
Russian_chrfpp_score_std,19.464846,19.781363,19.261181,17.833780,19.094084,17.729051,20.290879,20.912177,19.777378

In [6]:
df[df.index.str.startswith('Arabic')]

,default_nllb,prompt_nllb,replace_nllb,default_seamless,prompt_seamless,replace_seamless,default_gpt4omini,prompt_gpt4omini,replace_gpt4omini
Arabic_bleu_score_mean,14.932141,15.308997,14.888841,15.413104,16.911392,16.047758,14.062891,15.055060,14.142294
Arabic_bleu_score_std,14.697143,16.187722,14.757673,15.729298,17.930474,16.551117,14.662603,15.549691,14.313356
Arabic_bleu_1gram_precision_mean,15.038609,15.400722,14.991907,15.518274,17.018048,16.153225,14.107944,15.101355,14.191256
Arabic_bleu_1gram_precision_std,14.749332,16.229465,14.798824,15.781303,17.998912,16.606244,14.672883,15.567331,14.329737
Arabic_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_ref_len_mean,176.040000,177.646000,176.498000,178.930000,179.450000,179.422000,180.446000,180.864000,180.960000
Arabic_bleu_ref_len_std,63.724281,64.020825,63.867834,63.564345,63.802830,63.888178,64.802359,64.899718,65.175748
Arabic_bleu_pred_len_mean,176.066000,177.678000,176.512000,178.862000,179.418000,179.332000,180.804000,181.272000,181.268000
Arabic_bleu_pred_len_std,63.865415,63.992064,63.992781,63.663058,63.828516,63.922719,64.906481,64.983719,65.300386
Arabic_bleu_bp_mean,0.990933,0.991928,0.990970,0.992356,0.993000,0.992469,0.995762,0.996187,0.995628
Arabic_bleu_bp_std,0.020699,0.020042,0.020676,0.011166,0.010198,0.010597,0.009209,0.008226,0.009204
Arabic_bleu_ratio_mean,0.999937,1.000251,0.999910,0.999621,1.000006,0.999694,1.001918,1.002253,1.001561
Arabic_bleu_ratio_std,0.033510,0.031770,0.033556,0.023386,0.022256,0.023168,0.015425,0.014618,0.015392
Arabic_chrf_score_mean,15.469924,15.835513,15.422767,15.932627,17.442127,16.580276,14.521218,15.528536,14.604094
Arabic_chrf_score_std,14.990845,16.485200,15.043534,15.977988,18.165288,16.783763,14.843226,15.740950,14.504279
Arabic_ter_score_mean,101.723658,101.265382,101.769189,101.165345,99.199076,100.313853,102.554782,101.174810,102.334003
Arabic_ter_score_std,18.618565,20.301376,18.661581,19.991202,22.233324,20.597205,18.452606,19.203576,17.899233
Arabic_chrfpp_score_mean,15.469924,15.835513,15.422767,15.932627,17.442127,16.580276,14.521218,15.528536,14.604094
Arabic_chrfpp_score_std,14.990845,16.485200,15.043534,15.977988,18.165288,16.783763,14.843226,15.740950,14.504279

papers+model_cards

In [2]:
df_list = []
for model in ['nllb', 'seamless', 'gpt4omini']:
    df1 = pd.read_csv(f"/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/{model}.csv")
    res_g = get_mean_std_dict(df1)
    df2 = pd.read_csv(f"/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/{model}_prompt_gpt4omini.csv")
    res_s = get_mean_std_dict(df2)
    df_g = pd.DataFrame.from_dict(res_g, orient='index')
    df_g.columns = [f'default_{model}']
    df_s = pd.DataFrame.from_dict(res_s, orient='index')
    df_s.columns = [f'prompt_{model}']
    df_list.extend([df_g, df_s])
df = pd.concat(df_list, axis=1)
pd.set_option('display.max_rows', None)
df

,default_nllb,prompt_nllb,default_seamless,prompt_seamless,default_gpt4omini,prompt_gpt4omini
Chinese_bleu_score_mean,11.786008,12.568087,14.577784,15.361060,18.163403,18.613260
Chinese_bleu_score_std,13.226627,14.575323,16.253853,16.480512,19.071599,19.372648
Chinese_bleu_1gram_precision_mean,11.842334,12.645925,14.663101,15.461359,18.262754,18.717899
Chinese_bleu_1gram_precision_std,13.267864,14.627285,16.290439,16.537242,19.195887,19.499995
Chinese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_ref_len_mean,79.686000,80.482000,78.620000,81.296000,85.994000,85.944000
Chinese_bleu_ref_len_std,33.948792,34.060798,34.769029,35.315248,37.015866,36.971647
Chinese_bleu_pred_len_mean,83.708000,84.406000,81.920000,84.510000,89.454000,89.342000
Chinese_bleu_pred_len_std,36.903584,36.813634,36.974042,37.523672,38.640316,38.555598
Chinese_bleu_bp_mean,0.987602,0.988662,0.990953,0.991059,0.995720,0.995456
Chinese_bleu_bp_std,0.090323,0.079188,0.039519,0.036017,0.020121,0.020501
Chinese_bleu_ratio_mean,1.050481,1.048866,1.041064,1.038912,1.038656,1.038082
Chinese_bleu_ratio_std,0.129467,0.121024,0.074460,0.071187,0.055139,0.055177
Chinese_chrf_score_mean,12.428451,13.215857,15.243478,16.035738,18.872824,19.340585
Chinese_chrf_score_std,13.615382,15.006597,16.601074,16.787276,19.388336,19.702731
Chinese_ter_score_mean,99.364176,98.448421,96.024740,94.855533,91.394217,90.583412
Chinese_ter_score_std,20.252611,21.174378,22.616459,22.127501,24.280140,24.061265
Chinese_chrfpp_score_mean,12.428451,13.215857,15.243478,16.035738,18.872824,19.340585
Chinese_chrfpp_score_std,13.615382,15.006597,16.601074,16.787276,19.388336,19.702731
Arabic_bleu_score_mean,14.932141,15.308997,15.413104,16.911392,14.062891,15.055060
Arabic_bleu_score_std,14.697143,16.187722,15.729298,17.930474,14.662603,15.549691
Arabic_bleu_1gram_precision_mean,15.038609,15.400722,15.518274,17.018048,14.107944,15.101355
Arabic_bleu_1gram_precision_std,14.749332,16.229465,15.781303,17.998912,14.672883,15.567331
Arabic_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_ref_len_mean,176.040000,177.646000,178.930000,179.450000,180.446000,180.864000
Arabic_bleu_ref_len_std,63.724281,64.020825,63.564345,63.802830,64.802359,64.899718
Arabic_bleu_pred_len_mean,176.066000,177.678000,178.862000,179.418000,180.804000,181.272000
Arabic_bleu_pred_len_std,63.865415,63.992064,63.663058,63.828516,64.906481,64.983719
Arabic_bleu_bp_mean,0.990933,0.991928,0.992356,0.993000,0.995762,0.996187
Arabic_bleu_bp_std,0.020699,0.020042,0.011166,0.010198,0.009209,0.008226
Arabic_bleu_ratio_mean,0.999937,1.000251,0.999621,1.000006,1.001918,1.002253
Arabic_bleu_ratio_std,0.033510,0.031770,0.023386,0.022256,0.015425,0.014618
Arabic_chrf_score_mean,15.469924,15.835513,15.932627,17.442127,14.521218,15.528536
Arabic_chrf_score_std,14.990845,16.485200,15.977988,18.165288,14.843226,15.740950
Arabic_ter_score_mean,101.723658,101.265382,101.165345,99.199076,102.554782,101.174810
Arabic_ter_score_std,18.618565,20.301376,19.991202,22.233324,18.452606,19.203576
Arabic_chrfpp_score_mean,15.469924,15.835513,15.932627,17.442127,14.521218,15.528536
Arabic_chrfpp_score_std,14.990845,16.485200,15.977988,18.165288,14.843226,15.740950
French_bleu_score_mean,24.975488,25.117642,26.406360,29.570654,26.158622,27.965472
French_bleu_score_std,22.897323,22.918604,22.340410,24.270010,23.872646,26.068474
French_bleu_1gram_precision_mean,25.046143,25.175501,26.474438,29.624366,26.223490,28.024781
French_bleu_1gram_precision_std,22.927936,22.950041,22.374175,24.296072,23.901148,26.095104
French_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_ref_len_mean,206.090000,233.988000,242.870000,246.706000,251.474000,252.108000
French_bleu_ref_len_std,84.978566,89.157917,87.018421,87.524881,91.174926,91.049989
French_bleu_pred_len_mean,207.710000,235.634000,244.390000,248.348000,251.988000,252.676000
French_bleu_pred_len_std,85.866828,89.639648,87.788585,88.243349,91.335690,91.199329
French_bleu_bp_mean,0.996081,0.997156,0.996016,0.996754,0.996033,0.996471
French_bleu_bp_std,0.012978,0.008456,0.021401,0.021232,0.021156,0.020921
French_bleu_ratio_mean,1.008307,1.007946,1.005270,1.005792,1.001477,1.001681
French_bleu_ratio_std,0.033046,0.028165,0.025556,0.024477,0.021849,0.021260
French_chrf_score_mean,25.657747,25.796014,27.126048,30.327410,26.779602,28.570974
French_chrf_score_std,23.095562,23.135070,22.542258,24.452880,24.021731,26.177565
French_ter_score_mean,88.847077,88.663765,87.042842,83.332483,87.011173,84.845146
French_ter_score_std,28.020712,27.799828,27.203137,29.228578,28.626814,30.988302
French_chrfpp_score_mean,25.657747,25.796014,27.126048,30.327410,26.779602,28.570974
French_chrfpp_score_std,23.095562,23.135070,22.542258,24.452880,24.021731,26.177565
Japanese_bleu_score_mean,8.877999,9.498379,9.433089,10.060445,10.261729,10.674572
Japanese_bleu_score_std,11.195843,12.210791,11.701055,12.795067,12.427501,12.789017
Japanese_bleu_1gram_precision_mean,8.964482,9.574767,9.477468,10.104279,10.292917,10.709516
Japanese_bleu_1gram_precision_std,11.341098,12.346076,11.748187,12.838436,12.522672,12.893805
Japanese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_ref_len_mean,112.004000,112.920000,112.002000,112.532000,119.832000,119.404000
Japanese_bleu_ref_len_std,44.160302,43.924530,44.342785,43.719604,44.923223,44.673664
Japanese_bleu_pred_len_mean,115.970000,116.860000,116.910000,117.280000,124.938000,124.454000
Japanese_bleu_pred_len_std,46.859457,46.452385,46.744840,45.857556,47.152145,46.843147
Japanese_bleu_bp_mean,0.989911,0.991322,0.992803,0.995131,0.997058,0.996977
Japanese_bleu_bp_std,0.057086,0.052148,0.041459,0.025725,0.019513,0.019552
Japanese_bleu_ratio_mean,1.031891,1.032325,1.042668,1.042441,1.041394,1.041204
Japanese_bleu_ratio_std,0.088077,0.084324,0.076070,0.067920,0.049356,0.049498
Japanese_chrf_score_mean,9.271810,9.905175,9.903314,10.535247,10.703249,11.137465
Japanese_chrf_score_std,11.524890,12.563030,12.126059,13.214338,12.702369,13.082895
Japanese_ter_score_mean,100.637400,99.917637,99.979292,99.090232,98.778225,98.209088
Japanese_ter_score_std,16.129959,16.919971,16.831734,17.165030,17.441214,17.269685
Japanese_chrfpp_score_mean,9.271810,9.905175,9.903314,10.535247,10.703249,11.137465
Japanese_chrfpp_score_std,11.524890,12.563030,12.126059,13.214338,12.702369,13.082895
Russian_bleu_score_mean,18.859529,19.122750,18.402493,19.592972,18.889692,19.497648
Russian_bleu_score_std,19.266427,19.576512,17.667000,18.928593,20.143794,20.774576
Russian_bleu_1gram_precision_mean,18.918995,19.182352,18.452873,19.649588,18.971671,19.582059
Russian_bleu_1gram_precision_std,19.275649,19.589518,17.693548,18.960907,20.180779,20.817093
Russian_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Russian_bleu_ref_len_mean,200.064000,220.336000,228.910000,231.732000,236.248000,235.944000
Russian_bleu_ref_len_std,84.056164,85.083450,82.187197,83.397064,85.542138,85.436946
Russian_bleu_pred_len_mean,201.290000,221.442000,229.946000,232.762000,236.258000,235.926000
Russian_bleu_pred_len_std,85.186051,85.951859,83.176004,84.393304,85.966505,85.802194
Russian_bleu_bp_mean,0.995498,0.995707,0.995072,0.995092,0.994558,0.994556
Russian_bleu_bp_std,0.024599,0.024447,0.025523,0.025554,0.025522,0.025606
Russian_bleu_ratio_mean,1.004637,1.003881,1.002477,1.002515,0.998384,0.998326
Russian_bleu_ratio_std,0.029527,0.029496,0.027505,0.027334,0.024043,0.024064
Russian_chrf_score_mean,19.332506,19.603675,18.867215,20.074984,19.299636,19.908209
Russian_chrf_score_std,19.464846,19.781363,17.833780,19.094084,20.290879,20.912177
Russian_ter_score_mean,93.793137,93.470535,94.181978,92.716776,93.397718,92.640630
Russian_ter_score_std,23.418254,23.424508,21.341938,22.347377,23.978040,24.449049
Russian_chrfpp_score_mean,19.332506,19.603675,18.867215,20.074984,19.299636,19.908209
Russian_chrfpp_score_std,19.464846,19.781363,17.833780,19.094084,20.290879,20.912177