In [1]:
import pandas as pd
from multilingualmc.evaluator.eval_on_6060_gold import get_mean_std_dict

In [2]:
dataset_path = '/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/data_eval_6060/eval/gold_predictions_dev_'
# dataset_path = '/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/'

df_list = []
for model in ['nllb', 'seamless', 'gpt4omini', 'aya', 'aya_old']:
    df1 = pd.read_csv(f"{dataset_path}{model}.csv")
    res_g = get_mean_std_dict(df1)
    df2 = pd.read_csv(f"{dataset_path}{model}_prompt_gpt4omini.csv")
    res_s = get_mean_std_dict(df2)
    df3 = pd.read_csv(f"{dataset_path}{model}_hard_replace.csv")
    res_h = get_mean_std_dict(df3)
    
    df4 = pd.read_csv(f"{dataset_path}{model}_hard_replace_morphology.csv")
    res_m = get_mean_std_dict(df4)
    
    df_g = pd.DataFrame.from_dict(res_g, orient='index')
    df_g.columns = [f'default_{model}']
    df_s = pd.DataFrame.from_dict(res_s, orient='index')
    df_s.columns = [f'prompt_{model}']
    df_h = pd.DataFrame.from_dict(res_h, orient='index')
    df_h.columns = [f'replace_{model}']
    
    df_m = pd.DataFrame.from_dict(res_m, orient='index')
    df_m.columns = [f'replace_morphology_{model}']
    
    df_list.extend([df_g, df_s, df_h, df_m])
df = pd.concat(df_list, axis=1)
pd.set_option('display.max_rows', None)
df

,default_nllb,prompt_nllb,replace_nllb,replace_morphology_nllb,default_seamless,prompt_seamless,replace_seamless,replace_morphology_seamless,default_gpt4omini,prompt_gpt4omini,replace_gpt4omini,replace_morphology_gpt4omini,default_aya,prompt_aya,replace_aya,replace_morphology_aya,default_aya_old,prompt_aya_old,replace_aya_old,replace_morphology_aya_old
Chinese_bleu_score_mean,17.290322,19.206669,18.314578,19.692148,26.260466,27.233121,27.061354,29.010494,32.642742,34.244586,33.301260,34.121995,27.307034,28.633678,27.547309,27.840709,26.080908,26.547622,26.469119,26.529805
Chinese_bleu_score_std,22.884491,24.369353,24.255149,25.909276,24.838612,26.180706,25.587374,27.209619,29.927667,31.103996,30.515688,30.335484,27.556509,28.759337,27.731984,28.041718,25.689961,26.486721,25.628146,26.367415
Chinese_bleu_1gram_precision_mean,17.373744,19.299684,18.403496,19.743283,26.509304,27.500659,27.316012,29.206573,32.688419,34.301885,33.342434,34.164927,27.467022,28.750611,27.709862,27.957490,26.174877,26.641414,26.564691,26.623832
Chinese_bleu_1gram_precision_std,22.943895,24.428861,24.322354,25.956334,24.892197,26.229669,25.645436,27.263312,29.943006,31.118641,30.527881,30.345324,27.608389,28.800639,27.783104,28.103184,25.732219,26.526916,25.673681,26.403590
Chinese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_ref_len_mean,24.737179,26.523504,24.750000,26.104701,28.702991,29.352564,28.756410,29.134615,29.965812,30.021368,29.942308,29.970085,30.608974,30.472222,30.568376,30.508547,29.329060,29.358974,29.305556,29.371795
Chinese_bleu_ref_len_std,12.691587,13.492225,12.724199,13.398829,14.615538,14.695104,14.654788,14.605338,14.735894,14.786256,14.773337,14.747815,14.859906,14.926131,14.874695,14.980713,14.470773,14.483964,14.523798,14.487188
Chinese_bleu_pred_len_mean,24.589744,26.348291,24.604701,26.085470,28.241453,28.858974,28.297009,28.848291,30.023504,30.061966,30.000000,30.021368,30.538462,30.459402,30.495726,30.510684,29.254274,29.279915,29.230769,29.282051
Chinese_bleu_pred_len_std,12.456625,13.223675,12.492556,13.286062,13.910521,13.974487,13.958160,14.162277,14.726976,14.741106,14.765258,14.721962,14.806989,14.828948,14.820337,14.878879,14.235157,14.242044,14.289083,14.217850
Chinese_bleu_bp_mean,0.992534,0.992240,0.992587,0.996331,0.986352,0.985679,0.986387,0.990497,0.998458,0.998158,0.998448,0.998362,0.989951,0.993731,0.989898,0.994339,0.995322,0.995235,0.995321,0.995072
Chinese_bleu_bp_std,0.018462,0.020610,0.018336,0.013765,0.032179,0.032825,0.032071,0.028020,0.009488,0.011063,0.009547,0.009839,0.036690,0.023772,0.036800,0.022400,0.018082,0.018249,0.018085,0.018727
Chinese_bleu_ratio_mean,0.999040,0.998769,0.999091,1.002915,0.992778,0.992132,0.992809,0.996808,1.003576,1.003292,1.003567,1.003473,0.997874,1.001316,0.997825,1.001899,1.000892,1.000800,1.000891,1.000627
Chinese_bleu_ratio_std,0.033549,0.034589,0.033475,0.030745,0.043596,0.044084,0.043524,0.040400,0.022371,0.023072,0.022396,0.022511,0.041763,0.033291,0.041858,0.032309,0.027838,0.027939,0.027841,0.028221
Chinese_chrf_score_mean,17.445861,19.364672,18.471288,19.844374,26.429976,27.406624,27.232175,29.169333,32.758563,34.362966,33.416231,34.237316,27.515646,28.833561,27.757451,28.037702,26.195678,26.662387,26.585081,26.645633
Chinese_chrf_score_std,23.077840,24.540704,24.434113,26.069923,24.917690,26.250875,25.661643,27.271439,29.943774,31.113851,30.528578,30.345062,27.686476,28.876854,27.861866,28.164697,25.722465,26.516423,25.659289,26.395664
Chinese_ter_score_mean,83.259607,81.334455,82.229700,80.855268,74.315636,73.342357,73.514548,71.574865,67.787599,66.185270,67.129145,66.307205,73.465283,72.139846,73.224000,72.936689,74.395756,73.938828,74.017337,73.953724
Chinese_ter_score_std,23.012427,24.525858,24.396409,26.067374,25.214353,26.558167,25.969502,27.602086,30.201266,31.389308,30.792173,30.624114,27.919873,29.142219,28.097637,28.416354,25.987672,26.768444,25.914586,26.642950
Chinese_chrfpp_score_mean,17.445861,19.364672,18.471288,19.844374,26.429976,27.406624,27.232175,29.169333,32.758563,34.362966,33.416231,34.237316,27.515646,28.833561,27.757451,28.037702,26.195678,26.662387,26.585081,26.645633
Chinese_chrfpp_score_std,23.077840,24.540704,24.434113,26.069923,24.917690,26.250875,25.661643,27.271439,29.943774,31.113851,30.528578,30.345062,27.686476,28.876854,27.861866,28.164697,25.722465,26.516423,25.659289,26.395664
Arabic_bleu_score_mean,22.378510,23.748997,23.015090,23.584064,23.125221,24.283176,23.095773,25.476501,23.575632,24.642357,23.574303,24.075389,20.110562,21.341882,20.290822,21.355323,19.979696,20.516230,19.766412,20.557583
Arabic_bleu_score_std,24.433796,25.891488,24.919642,25.481021,24.717578,25.843338,24.565077,27.264149,26.626305,27.852527,26.397384,27.155443,23.090681,24.679582,23.434380,24.391785,22.345625,23.486622,22.136153,23.368714
Arabic_bleu_1gram_precision_mean,22.481185,23.850015,23.132751,23.665323,23.190607,24.351047,23.182162,25.529756,23.623527,24.692755,23.636591,24.126678,20.196255,21.426985,20.382036,21.434060,20.031091,20.573583,19.816113,20.613669
Arabic_bleu_1gram_precision_std,24.466629,25.922259,24.963391,25.509804,24.723356,25.849943,24.590308,27.267634,26.643278,27.863641,26.426864,27.179270,23.139717,24.730800,23.489130,24.444100,22.366019,23.502925,22.146055,23.400494
Arabic_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_ref_len_mean,70.179487,70.311966,70.331197,70.224359,69.557692,69.794872,69.841880,69.722222,70.403846,70.589744,70.670940,70.608974,71.538462,71.474359,71.698718,71.356838,69.717949,69.929487,69.912393,69.914530
Arabic_bleu_ref_len_std,35.624887,35.596431,35.844766,35.666353,35.323208,35.540076,35.557725,35.545907,35.876742,35.951288,36.137298,36.105646,36.097842,36.293849,36.276966,36.333319,35.738845,36.016314,35.926984,35.826210
Arabic_bleu_pred_len_mean,70.076923,70.235043,70.173077,70.250000,69.638889,69.886752,69.829060,69.886752,70.677350,70.846154,70.876068,70.869658,71.794872,71.745726,71.925214,71.679487,69.989316,70.196581,70.138889,70.211538
Arabic_bleu_pred_len_std,35.401800,35.411141,35.623146,35.565898,35.109677,35.313372,35.300737,35.372626,35.922599,36.001395,36.143919,36.139660,36.241585,36.426593,36.392648,36.466344,35.685485,35.972983,35.849853,35.789656
Arabic_bleu_bp_mean,0.993848,0.994057,0.993280,0.995148,0.995650,0.995805,0.995008,0.996371,0.997010,0.996960,0.996671,0.996989,0.994522,0.994978,0.994318,0.995458,0.996277,0.996052,0.996002,0.996493
Arabic_bleu_bp_std,0.012290,0.012105,0.012495,0.010040,0.010094,0.009974,0.010512,0.009501,0.007686,0.007823,0.007924,0.007662,0.012690,0.012098,0.012767,0.011305,0.008906,0.009193,0.009328,0.008673
Arabic_bleu_ratio_mean,0.999998,1.000140,0.999115,1.001501,1.003774,1.004012,1.002502,1.004896,1.005268,1.004971,1.004370,1.005156,1.003991,1.004447,1.003681,1.005344,1.006085,1.005961,1.005432,1.006406
Arabic_bleu_ratio_std,0.020215,0.019876,0.020351,0.018677,0.021011,0.021036,0.021287,0.020627,0.018529,0.018429,0.018731,0.018547,0.022087,0.021782,0.022410,0.021302,0.021166,0.021533,0.021436,0.021017
Arabic_chrf_score_mean,22.866878,24.241355,23.507353,24.083585,23.669377,24.834704,23.638566,26.027251,24.061222,25.130929,24.058351,24.564211,20.616403,21.853957,20.795396,21.872497,20.496838,21.033306,20.283923,21.076176
Arabic_chrf_score_std,24.559764,26.015277,25.041617,25.612102,24.917418,26.039628,24.780745,27.437161,26.761625,27.975127,26.549977,27.282434,23.258148,24.826284,23.603902,24.540651,22.541848,23.652054,22.339221,23.535154
Arabic_ter_score_mean,91.116206,89.527814,90.373087,89.777208,90.274368,88.940501,90.285385,87.496505,89.659759,88.485798,89.544900,89.116725,93.612334,92.266797,93.369596,92.255265,93.970507,93.401165,94.195706,93.361205
Arabic_ter_score_std,29.394228,31.075329,29.943290,30.629866,29.629773,30.996696,29.450984,32.615811,32.089092,33.431811,31.739644,32.652339,27.748853,29.575337,28.116342,29.272870,26.964452,28.237885,26.688320,28.171262
Arabic_chrfpp_score_mean,22.866878,24.241355,23.507353,24.083585,23.669377,24.834704,23.638566,26.027251,24.061222,25.130929,24.058351,24.564211,20.616403,21.853957,20.795396,21.872497,20.496838,21.033306,20.283923,21.076176
Arabic_chrfpp_score_std,24.559764,26.015277,25.041617,25.612102,24.917418,26.039628,24.780745,27.437161,26.761625,27.975127,26.549977,27.282434,23.258148,24.826284,23.603902,24.540651,22.541848,23.652054,22.339221,23.535154
French_bleu_score_mean,34.926450,37.783142,35.140132,38.156800,40.036811,42.119966,39.468810,41.724654,40.799976,43.881947,41.296968,43.181829,33.046740,35.504507,33.243398,35.020398,33.852287,36.129970,33.744477,36.334371
French_bleu_score_std,29.698674,31.328180,29.689336,31.981868,31.350857,32.613398,31.609056,32.248232,32.287764,33.651007,32.306443,33.314634,28.461718,30.641584,28.719165,30.279824,28.539771,30.460717,28.574047,30.767894
French_bleu_1gram_precision_mean,35.096053,37.910472,35.309060,38.283809,40.170630,42.223802,39.597737,41.841357,40.902289,43.979812,41.410110,43.274584,33.183519,35.624960,33.379040,35.145214,33.981715,36.228457,33.870530,36.436892
French_bleu_1gram_precision_std,29.756848,31.372444,29.745387,32.020560,31.382584,32.634397,31.640102,32.289400,32.302941,33.673254,32.322543,33.329041,28.501638,30.674352,28.749380,30.324839,28.571815,30.483543,28.602095,30.791846
French_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_ref_len_mean,100.591880,101.307692,101.115385,101.262821,101.485043,101.822650,101.869658,102.014957,102.425214,102.863248,102.681624,102.852564,102.369658,102.523504,102.655983,102.707265,100.782051,101.153846,101.185897,101.292735
French_bleu_ref_len_std,48.914711,49.797055,49.062163,49.161158,50.106031,50.224086,50.161902,50.245498,49.811903,50.115525,49.937039,50.071359,49.917599,50.068705,49.961390,50.025280,49.884573,49.815181,49.919010,49.923858
French_bleu_pred_len_mean,100.420940,101.367521,100.882479,101.262821,101.555556,101.991453,101.880342,102.132479,102.542735,102.978632,102.717949,102.967949,102.367521,102.615385,102.615385,102.773504,100.702991,101.222222,101.068376,101.320513
French_bleu_pred_len_std,48.753544,49.739036,48.841143,49.018213,49.983328,50.115198,49.975054,50.112204,49.765320,50.046826,49.836408,49.982149,49.760428,49.915234,49.769636,49.852802,49.635798,49.637420,49.606067,49.728512
French_bleu_bp_mean,0.993571,0.995451,0.993513,0.995258,0.995285,0.996389,0.995220,0.996145,0.996366,0.996816,0.996122,0.996731,0.994804,0.995697,0.994753,0.995624,0.994517,0.995974,0.994575,0.995828
French_bleu_bp_std,0.013270,0.010774,0.012936,0.010853,0.011612,0.009680,0.010854,0.009845,0.007942,0.007319,0.007947,0.007398,0.010027,0.008765,0.009546,0.008592,0.010447,0.008114,0.010000,0.008411
French_bleu_ratio_mean,0.999553,1.001795,0.999110,1.001297,1.002176,1.003228,1.001818,1.002725,1.002492,1.002557,1.001854,1.002669,1.001711,1.002748,1.001480,1.002515,1.001232,1.002585,1.001097,1.002234
French_bleu_ratio_std,0.020479,0.018686,0.020118,0.018782,0.020454,0.018977,0.019966,0.019190,0.016750,0.016146,0.016684,0.016442,0.020514,0.019709,0.020254,0.019613,0.020224,0.018580,0.019915,0.018712
French_chrf_score_mean,35.550164,38.404879,35.761919,38.763020,40.681631,42.757871,40.099758,42.354105,41.398729,44.456365,41.890977,43.767284,33.679375,36.122484,33.864073,35.640896,34.483032,36.742936,34.373297,36.938198
French_chrf_score_std,29.852089,31.438756,29.834345,32.079033,31.391065,32.640913,31.646244,32.264571,32.268753,33.607798,32.278230,33.278240,28.564849,30.705276,28.811121,30.359479,28.628510,30.525470,28.661256,30.824204
French_ter_score_mean,75.208495,71.966890,74.946715,71.493337,69.192875,66.813188,69.846949,67.286171,68.324760,64.755437,67.768374,65.564264,77.430891,74.646827,77.196079,75.152537,76.350227,73.707667,76.529713,73.463983
French_ter_score_std,34.894978,36.824220,34.806464,37.491114,36.779285,38.175514,36.995249,37.777774,37.852810,39.393793,37.847697,39.016867,33.498900,35.998566,33.748437,35.544797,33.535861,35.720276,33.569831,36.110634
French_chrfpp_score_mean,35.550164,38.404879,35.761919,38.763020,40.681631,42.757871,40.099758,42.354105,41.398729,44.456365,41.890977,43.767284,33.679375,36.122484,33.864073,35.640896,34.483032,36.742936,34.373297,36.938198
French_chrfpp_score_std,29.852089,31.438756,29.834345,32.079033,31.391065,32.640913,31.646244,32.264571,32.268753,33.607798,32.278230,33.278240,28.564849,30.705276,28.811121,30.359479,28.628510,30.525470,28.661256,30.824204
Japanese_bleu_score_mean,6.189753,8.608340,6.716573,9.137019,14.560215,15.300357,14.609585,16.942646,21.463774,22.107881,21.658574,22.400145,14.593544,15.208309,14.917592,15.674884,15.063128,15.937722,15.427966,16.305524
Japanese_bleu_score_std,12.899605,16.147445,13.588380,17.185116,20.150848,20.984092,19.699521,22.630005,23.805727,24.768802,23.933249,25.263679,18.195788,18.910561,18.419860,20.057322,18.767392,19.654305,18.648891,20.245983
Japanese_bleu_1gram_precision_mean,6.256093,8.668448,6.792577,9.179558,14.713092,15.433310,14.764669,17.016096,21.466157,22.110344,21.660957,22.402609,14.601803,15.212979,14.924634,15.679554,15.069197,15.945203,15.435039,16.311037
Japanese_bleu_1gram_precision_std,12.942535,16.171423,13.640266,17.202267,20.297964,21.099900,19.858559,22.679320,23.805461,24.768520,23.932965,25.263374,18.199294,18.910961,18.421714,20.057591,18.768683,19.655452,18.650327,20.246842
Japanese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_ref_len_mean,36.224359,38.301282,36.512821,38.175214,40.606838,40.929487,40.735043,41.083333,43.574786,43.542735,43.591880,43.566239,43.773504,43.835470,43.856838,43.863248,42.551282,42.758547,42.643162,42.732906
Japanese_bleu_ref_len_std,20.171505,20.982123,20.195772,20.764491,19.848660,20.049653,19.909492,20.136778,21.172908,21.104316,21.076848,21.147638,21.074254,21.096309,21.021729,21.097269,21.058792,21.058993,21.014393,20.947554
Japanese_bleu_pred_len_mean,35.450855,37.756410,35.739316,37.850427,40.237179,40.660256,40.365385,40.982906,43.884615,43.852564,43.901709,43.876068,44.094017,44.160256,44.177350,44.188034,42.805556,43.010684,42.897436,43.000000
Japanese_bleu_pred_len_std,19.733876,20.624834,19.751464,20.742509,19.701557,19.966298,19.759069,20.100596,21.206528,21.139023,21.111283,21.183142,21.070386,21.092078,21.017189,21.093016,21.028547,21.030464,20.984907,20.949210
Japanese_bleu_bp_mean,0.976870,0.983362,0.977065,0.987209,0.987075,0.989289,0.987133,0.993278,0.999834,0.999832,0.999834,0.999832,0.999232,0.999323,0.999232,0.999323,0.999499,0.999438,0.999491,0.999644
Japanese_bleu_bp_std,0.033611,0.032317,0.033392,0.029445,0.023912,0.023300,0.023806,0.018214,0.002539,0.002566,0.002539,0.002566,0.005960,0.005637,0.005960,0.005637,0.004952,0.005328,0.004982,0.004564
Japanese_bleu_ratio_mean,0.980444,0.986999,0.980628,0.990888,0.992280,0.994419,0.992326,0.998316,1.008894,1.008890,1.008887,1.008881,1.010368,1.010457,1.010364,1.010482,1.008755,1.008671,1.008739,1.008890

In [10]:
# model = "nllb"
# model = "seamless"
# model = "gpt4omini"
# model = "aya_old"
# model = "aya"
for metric in ['BLEU', 'ChrF', 'ChrF++', 'TER']:
    print("\n" + metric)
    for model, model_name in [['nllb', 'nllb-200-3.3B'], ['seamless', 'hf-seamless-m4t-large'], ['gpt4omini', 'gpt-4o-mini'], ['aya_old', 'aya-23-8B'], ['aya', 'aya-expanse-8B']]:
        print(r"""\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{""" + model_name + r"""}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}""")
        
        for tgt_lang in ['Arabic', 'Chinese', 'French', 'Japanese', 'Russian']:
            tmp = df[df.index.str.startswith(tgt_lang)]
            # Function to modify the indices as specified
            def modify_index(index):
                parts = index.split("_")
                new_index = " ".join(parts[1:])  # Remove the first element and join the rest with spaces
                return new_index.capitalize()   # Capitalize the first character

            tmp.index = tmp.index.map(modify_index)
            cols = [col for col in tmp.columns if model in col]
            # tmp.rename(columns = {f"default_{model}": "Direct Translation", f"prompt_{model}": "Prompting Refinement", f"replace_{model}": "Word Alignment"}, inplace=True)
            # print(tmp[["Direct Translation", "Prompting Refinement", "Word Alignment"]].to_latex(float_format="%.2f"))

            tmp.rename(
                columns={
                    f"default_{model}": "Direct Translation",
                    f"prompt_{model}": "Prompting Refinement",
                    f"replace_{model}": "Word Alignment",
                    f"replace_morphology_{model}": "Morphological Word Alignment",
                },
                index={
                    "Bleu score mean": "BLEU",
                    "Chrf score mean": "ChrF",
                    "Chrfpp score mean": "ChrF++",
                    "Ter score mean": "TER",
                },
                inplace=True,
            )
            print(
                tgt_lang + " & " + " & ".join(tmp[
                    [
                        "Direct Translation",
                        "Prompting Refinement",
                        "Word Alignment",
                        "Morphological Word Alignment",
                    ]
                ]
                .loc[[metric]]
                .iloc[0]
                .map(lambda x: f"{x:.2f}" if isinstance(x, float) else str(x))) + " \\\\"
                # .head(1)
                # .to_latex(float_format="%.2f", header=False)
                
            )

BLEU
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{nllb-200-3.3B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 22.38 & 23.75 & 23.02 & 23.58 \\
Chinese & 17.29 & 19.21 & 18.31 & 19.69 \\
French & 34.93 & 37.78 & 35.14 & 38.16 \\
Japanese & 6.19 & 8.61 & 6.72 & 9.14 \\
Russian & 17.30 & 18.84 & 18.37 & 18.81 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{hf-seamless-m4t-large}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 23.13 & 24.28 & 23.10 & 25.48 \\
Chinese & 26.26 & 27.23 & 27.06 & 29.01 \\
French & 40.04 & 42.12 & 39.47 & 41.72 \\
Japanese & 14.56 & 15.30 & 14.61 & 16.94 \\
Russian & 17.18 & 18.88 & 18.34 & 18.40 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{gpt-4o-mini}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 23.58 & 24.64 & 23.57 & 24.08 \\
Chinese & 32.64 & 34.24 & 33.30 & 34.12 \\
French & 40.80 & 43.88 & 41.30 & 43.18 \\
Japanese & 21.46 & 22.11 & 21.66 & 22.40 \\
Russian & 17.25 & 18.33 & 17.12 & 17.81 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-23-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 19.98 & 20.52 & 19.77 & 20.56 \\
Chinese & 26.08 & 26.55 & 26.47 & 26.53 \\
French & 33.85 & 36.13 & 33.74 & 36.33 \\
Japanese & 15.06 & 15.94 & 15.43 & 16.31 \\
Russian & 15.77 & 16.83 & 16.14 & 16.61 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-expanse-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 20.11 & 21.34 & 20.29 & 21.36 \\
Chinese & 27.31 & 28.63 & 27.55 & 27.84 \\
French & 33.05 & 35.50 & 33.24 & 35.02 \\
Japanese & 14.59 & 15.21 & 14.92 & 15.67 \\
Russian & 16.59 & 18.18 & 16.54 & 17.52 \\

ChrF
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{nllb-200-3.3B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 22.87 & 24.24 & 23.51 & 24.08 \\
Chinese & 17.45 & 19.36 & 18.47 & 19.84 \\
French & 35.55 & 38.40 & 35.76 & 38.76 \\
Japanese & 6.22 & 8.64 & 6.75 & 9.17 \\
Russian & 17.69 & 19.24 & 18.77 & 19.22 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{hf-seamless-m4t-large}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 23.67 & 24.83 & 23.64 & 26.03 \\
Chinese & 26.43 & 27.41 & 27.23 & 29.17 \\
French & 40.68 & 42.76 & 40.10 & 42.35 \\
Japanese & 14.65 & 15.39 & 14.70 & 17.02 \\
Russian & 17.61 & 19.33 & 18.79 & 18.84 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{gpt-4o-mini}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 24.06 & 25.13 & 24.06 & 24.56 \\
Chinese & 32.76 & 34.36 & 33.42 & 34.24 \\
French & 41.40 & 44.46 & 41.89 & 43.77 \\
Japanese & 21.59 & 22.24 & 21.79 & 22.53 \\
Russian & 17.65 & 18.73 & 17.52 & 18.21 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-23-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 20.50 & 21.03 & 20.28 & 21.08 \\
Chinese & 26.20 & 26.66 & 26.59 & 26.65 \\
French & 34.48 & 36.74 & 34.37 & 36.94 \\
Japanese & 15.22 & 16.10 & 15.59 & 16.47 \\
Russian & 16.17 & 17.23 & 16.54 & 17.02 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-expanse-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 20.62 & 21.85 & 20.80 & 21.87 \\
Chinese & 27.52 & 28.83 & 27.76 & 28.04 \\
French & 33.68 & 36.12 & 33.86 & 35.64 \\
Japanese & 14.76 & 15.37 & 15.08 & 15.84 \\
Russian & 16.99 & 18.57 & 16.92 & 17.91 \\

ChrF++
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{nllb-200-3.3B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 22.87 & 24.24 & 23.51 & 24.08 \\
Chinese & 17.45 & 19.36 & 18.47 & 19.84 \\
French & 35.55 & 38.40 & 35.76 & 38.76 \\
Japanese & 6.22 & 8.64 & 6.75 & 9.17 \\
Russian & 17.69 & 19.24 & 18.77 & 19.22 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{hf-seamless-m4t-large}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 23.67 & 24.83 & 23.64 & 26.03 \\
Chinese & 26.43 & 27.41 & 27.23 & 29.17 \\
French & 40.68 & 42.76 & 40.10 & 42.35 \\
Japanese & 14.65 & 15.39 & 14.70 & 17.02 \\
Russian & 17.61 & 19.33 & 18.79 & 18.84 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{gpt-4o-mini}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 24.06 & 25.13 & 24.06 & 24.56 \\
Chinese & 32.76 & 34.36 & 33.42 & 34.24 \\
French & 41.40 & 44.46 & 41.89 & 43.77 \\
Japanese & 21.59 & 22.24 & 21.79 & 22.53 \\
Russian & 17.65 & 18.73 & 17.52 & 18.21 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-23-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 20.50 & 21.03 & 20.28 & 21.08 \\
Chinese & 26.20 & 26.66 & 26.59 & 26.65 \\
French & 34.48 & 36.74 & 34.37 & 36.94 \\
Japanese & 15.22 & 16.10 & 15.59 & 16.47 \\
Russian & 16.17 & 17.23 & 16.54 & 17.02 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-expanse-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 20.62 & 21.85 & 20.80 & 21.87 \\
Chinese & 27.52 & 28.83 & 27.76 & 28.04 \\
French & 33.68 & 36.12 & 33.86 & 35.64 \\
Japanese & 14.76 & 15.37 & 15.08 & 15.84 \\
Russian & 16.99 & 18.57 & 16.92 & 17.91 \\

TER
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{nllb-200-3.3B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 91.12 & 89.53 & 90.37 & 89.78 \\
Chinese & 83.26 & 81.33 & 82.23 & 80.86 \\
French & 75.21 & 71.97 & 74.95 & 71.49 \\
Japanese & 94.32 & 91.91 & 93.79 & 91.38 \\
Russian & 93.87 & 92.19 & 92.70 & 92.21 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{hf-seamless-m4t-large}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 90.27 & 88.94 & 90.29 & 87.50 \\
Chinese & 74.32 & 73.34 & 73.51 & 71.57 \\
French & 69.19 & 66.81 & 69.85 & 67.29 \\
Japanese & 86.02 & 85.28 & 85.97 & 83.65 \\
Russian & 94.01 & 92.13 & 92.71 & 92.64 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{gpt-4o-mini}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 89.66 & 88.49 & 89.54 & 89.12 \\
Chinese & 67.79 & 66.19 & 67.13 & 66.31 \\
French & 68.32 & 64.76 & 67.77 & 65.56 \\
Japanese & 79.33 & 78.68 & 79.13 & 78.39 \\
Russian & 93.90 & 92.73 & 94.05 & 93.32 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-23-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 93.97 & 93.40 & 94.20 & 93.36 \\
Chinese & 74.40 & 73.94 & 74.02 & 73.95 \\
French & 76.35 & 73.71 & 76.53 & 73.46 \\
Japanese & 85.73 & 84.86 & 85.37 & 84.49 \\
Russian & 95.60 & 94.42 & 95.15 & 94.62 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-expanse-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 93.61 & 92.27 & 93.37 & 92.26 \\
Chinese & 73.47 & 72.14 & 73.22 & 72.94 \\
French & 77.43 & 74.65 & 77.20 & 75.15 \\
Japanese & 86.42 & 85.81 & 86.10 & 85.34 \\
Russian & 94.56 & 92.82 & 94.64 & 93.60 \\

/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/1759042992.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(

papers+model_cards

In [11]:
dataset_path = "/home/jiaruil5/multilingual/multilingual-model-card/multilingualmc/dataset/eval/"

df_list = []
for model in ['nllb', 'seamless', 'gpt4omini', 'aya', 'aya_old']:
    df1 = pd.read_csv(f"{dataset_path}{model}.csv")
    res_g = get_mean_std_dict(df1)
    df2 = pd.read_csv(f"{dataset_path}{model}_prompt_gpt4omini.csv")
    res_s = get_mean_std_dict(df2)
    df3 = pd.read_csv(f"{dataset_path}{model}_hard_replace.csv")
    res_h = get_mean_std_dict(df3)
    
    df4 = pd.read_csv(f"{dataset_path}{model}_hard_replace_morphology.csv")
    res_m = get_mean_std_dict(df4)
    
    df_g = pd.DataFrame.from_dict(res_g, orient='index')
    df_g.columns = [f'default_{model}']
    df_s = pd.DataFrame.from_dict(res_s, orient='index')
    df_s.columns = [f'prompt_{model}']
    df_h = pd.DataFrame.from_dict(res_h, orient='index')
    df_h.columns = [f'replace_{model}']
    
    df_m = pd.DataFrame.from_dict(res_m, orient='index')
    df_m.columns = [f'replace_morphology_{model}']
    
    df_list.extend([df_g, df_s, df_h, df_m])
df = pd.concat(df_list, axis=1)
pd.set_option('display.max_rows', None)
df

,default_nllb,prompt_nllb,replace_nllb,replace_morphology_nllb,default_seamless,prompt_seamless,replace_seamless,replace_morphology_seamless,default_gpt4omini,prompt_gpt4omini,replace_gpt4omini,replace_morphology_gpt4omini,default_aya,prompt_aya,replace_aya,replace_morphology_aya,default_aya_old,prompt_aya_old,replace_aya_old,replace_morphology_aya_old
Chinese_bleu_score_mean,10.242714,12.434321,12.311245,13.338462,13.670800,14.767024,14.397723,15.664235,17.213856,18.437501,18.601331,18.550447,12.040152,12.983537,12.206943,12.891491,14.503380,14.897192,14.697194,15.214704
Chinese_bleu_score_std,11.679866,14.394978,13.708840,15.658893,15.285313,15.792532,16.035155,17.123853,18.755439,19.493859,19.249274,19.198927,13.459609,14.415012,13.424830,14.611427,15.361172,16.071713,15.519775,17.084799
Chinese_bleu_1gram_precision_mean,10.291600,12.511687,12.376091,13.400848,13.747659,14.857384,14.481115,15.733902,17.349188,18.542179,18.702142,18.648960,12.077673,13.029484,12.240863,12.936638,14.582532,14.979879,14.775246,15.297782
Chinese_bleu_1gram_precision_std,11.716468,14.447440,13.755332,15.683909,15.307116,15.844228,16.080810,17.152462,18.949378,19.622701,19.376625,19.320313,13.511118,14.469232,13.463487,14.665343,15.490775,16.195959,15.646165,17.208303
Chinese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Chinese_bleu_ref_len_mean,75.920833,80.178000,79.388000,80.246000,75.672340,81.096000,78.320000,79.154000,83.213675,85.582000,85.496000,85.222000,86.460000,86.230000,86.482000,86.246000,84.040000,84.570000,84.064000,84.320000
Chinese_bleu_ref_len_std,31.478325,32.633544,32.595189,32.878008,34.877304,34.035564,33.848501,33.955563,36.034992,35.240588,35.334502,35.179310,36.212361,36.186406,36.241420,36.163865,35.536123,35.277104,35.580160,35.653386
Chinese_bleu_pred_len_mean,79.716667,84.074000,83.376000,84.512000,78.804255,84.240000,81.608000,82.812000,86.683761,88.986000,88.962000,88.762000,92.340000,91.986000,92.374000,91.940000,87.662000,88.194000,87.686000,87.934000
Chinese_bleu_pred_len_std,34.398522,35.193546,35.407372,35.677663,36.633376,35.877301,35.877859,36.023382,37.806975,37.004005,37.096967,36.950345,39.901838,39.678844,39.941065,39.645579,37.738630,37.489456,37.809503,37.864615
Chinese_bleu_bp_mean,0.983121,0.988634,0.987523,0.989861,0.988255,0.991349,0.991186,0.992415,0.994871,0.995101,0.995552,0.995751,0.997611,0.997321,0.997630,0.997340,0.995748,0.995740,0.995636,0.996032
Chinese_bleu_bp_std,0.112088,0.079247,0.090425,0.078753,0.053936,0.035904,0.039253,0.034306,0.023482,0.020904,0.020252,0.019775,0.014593,0.015546,0.014558,0.015257,0.016880,0.016868,0.017033,0.016180
Chinese_bleu_ratio_mean,1.044392,1.049157,1.050477,1.053467,1.040781,1.038650,1.041355,1.046054,1.039457,1.037837,1.038712,1.039852,1.067658,1.067645,1.067772,1.066875,1.041691,1.041475,1.041593,1.041343
Chinese_bleu_ratio_std,0.142129,0.121411,0.129448,0.123189,0.084048,0.070069,0.074338,0.074918,0.059273,0.056303,0.056083,0.057145,0.084695,0.089404,0.084557,0.089556,0.064054,0.063421,0.064426,0.060818
Chinese_chrf_score_mean,10.818115,13.078094,12.981049,14.029782,14.335074,15.416832,15.059122,16.389031,17.929379,19.155705,19.316707,19.294751,12.764389,13.744460,12.942150,13.629910,15.117807,15.517665,15.319583,15.826467
Chinese_chrf_score_std,12.048005,14.822428,14.155486,16.072652,15.650703,16.095755,16.379360,17.438947,19.103667,19.821948,19.560853,19.561839,13.861209,14.806861,13.831860,14.968508,15.651691,16.349280,15.805402,17.317906
Chinese_ter_score_mean,101.050254,98.596512,98.464688,97.589064,97.259602,95.496428,96.192901,94.644395,93.005075,90.776891,90.551394,90.767096,99.335603,98.294132,99.127695,98.393451,95.183775,94.489478,94.762121,94.212346
Chinese_ter_score_std,19.343155,21.012149,19.971557,22.286493,22.316460,21.458254,22.404142,22.824209,24.890227,24.171000,24.001004,24.030709,20.494251,21.515466,20.535763,21.819539,20.333872,20.540301,20.074740,21.674471
Chinese_chrfpp_score_mean,10.818115,13.078094,12.981049,14.029782,14.335074,15.416832,15.059122,16.389031,17.929379,19.155705,19.316707,19.294751,12.764389,13.744460,12.942150,13.629910,15.117807,15.517665,15.319583,15.826467
Chinese_chrfpp_score_std,12.048005,14.822428,14.155486,16.072652,15.650703,16.095755,16.379360,17.438947,19.103667,19.821948,19.560853,19.561839,13.861209,14.806861,13.831860,14.968508,15.651691,16.349280,15.805402,17.317906
Arabic_bleu_score_mean,15.422320,15.115546,14.656182,15.712719,15.380512,16.475314,15.828079,17.037902,14.369848,14.904206,13.948369,14.982259,11.466253,11.831425,11.569323,11.958414,14.276065,15.084099,14.552532,15.028612
Arabic_bleu_score_std,15.757688,16.022553,14.645035,16.232922,16.322209,17.523945,16.007964,17.912786,16.316026,15.577164,14.301622,15.594280,10.750150,11.919580,11.657750,11.658472,14.759463,16.234804,15.037904,16.467228
Arabic_bleu_1gram_precision_mean,15.538449,15.208924,14.759500,15.785181,15.500843,16.579364,15.932719,17.111806,14.420813,14.950095,13.996590,15.027924,11.497554,11.861445,11.605224,11.989708,14.343533,15.149451,14.625987,15.090872
Arabic_bleu_1gram_precision_std,15.825797,16.064783,14.683071,16.273698,16.398694,17.583733,16.063546,17.960656,16.324274,15.590877,14.316620,15.611555,10.777925,11.940562,11.688230,11.689887,14.824631,16.293928,15.107723,16.528369
Arabic_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Arabic_bleu_ref_len_mean,169.012500,177.836000,176.634000,176.926000,173.421277,179.996000,179.570000,179.610000,174.175214,181.134000,181.070000,180.954000,183.006000,183.176000,183.274000,182.992000,177.822000,179.164000,178.202000,178.226000
Arabic_bleu_ref_len_std,65.197959,64.392374,63.908628,64.274653,66.220536,64.012461,63.904685,63.925385,67.357983,65.074060,65.154334,64.854453,66.108931,66.206371,66.101572,66.255835,65.994461,65.718940,66.072175,65.787376
Arabic_bleu_pred_len_mean,168.720833,177.874000,176.632000,177.588000,173.412766,179.914000,179.472000,180.172000,174.264957,181.550000,181.374000,181.400000,185.578000,185.770000,185.766000,185.578000,178.212000,179.608000,178.542000,178.724000
Arabic_bleu_pred_len_std,64.707074,64.405545,64.062318,64.613684,66.224655,64.042560,63.990271,64.305184,67.263608,65.193158,65.311234,65.042148,66.509540,66.567948,66.439926,66.662040,66.059631,65.784326,66.133922,65.837474
Arabic_bleu_bp_mean,0.989220,0.991739,0.990807,0.993810,0.991618,0.992903,0.992383,0.995069,0.994984,0.996135,0.995607,0.996134,0.997441,0.997463,0.997184,0.997477,0.995205,0.995627,0.995032,0.995836
Arabic_bleu_bp_std,0.027578,0.020209,0.020901,0.019749,0.012440,0.010356,0.010778,0.008751,0.010682,0.008342,0.009329,0.008371,0.005647,0.005628,0.005837,0.005525,0.010257,0.009614,0.010275,0.009248
Arabic_bleu_ratio_mean,0.998364,1.000158,0.999760,1.003428,0.999859,0.999734,0.999572,1.003246,1.000744,1.002228,1.001460,1.002303,1.017177,1.018181,1.016837,1.018097,1.002958,1.003212,1.002627,1.003614
Arabic_bleu_ratio_std,0.037576,0.032118,0.033689,0.032109,0.026821,0.022139,0.023165,0.021837,0.016178,0.014620,0.015151,0.014878,0.045469,0.053311,0.046066,0.053356,0.023662,0.022702,0.023418,0.022796
Arabic_chrf_score_mean,15.953943,15.638617,15.181188,16.249587,15.900145,17.004960,16.361428,17.576607,14.822451,15.372945,14.404917,15.450131,11.946944,12.315622,12.048075,12.450595,14.772349,15.587452,15.054715,15.526092
Arabic_chrf_score_std,16.000618,16.315065,14.925555,16.536224,16.567444,17.758317,16.251184,18.141893,16.465534,15.763233,14.489958,15.773916,11.004080,12.150554,11.884715,11.917169,15.023965,16.489904,15.293385,16.713350
Arabic_ter_score_mean,101.291139,101.465461,101.998009,100.820218,101.337129,99.860797,100.565534,99.148482,102.333077,101.290215,102.579849,101.174959,106.349068,106.046743,106.221271,105.882406,102.453201,101.529420,102.085105,101.544323
Arabic_ter_score_std,20.204467,20.060867,18.573230,20.578044,21.115344,21.794658,19.972373,22.402896,20.704111,19.205322,17.920084,19.258702,15.124725,16.631409,15.957943,16.354307,18.875750,20.353787,18.949221,20.634817
Arabic_chrfpp_score_mean,15.953943,15.638617,15.181188,16.249587,15.900145,17.004960,16.361428,17.576607,14.822451,15.372945,14.404917,15.450131,11.946944,12.315622,12.048075,12.450595,14.772349,15.587452,15.054715,15.526092
Arabic_chrfpp_score_std,16.000618,16.315065,14.925555,16.536224,16.567444,17.758317,16.251184,18.141893,16.465534,15.763233,14.489958,15.773916,11.004080,12.150554,11.884715,11.917169,15.023965,16.489904,15.293385,16.713350
French_bleu_score_mean,22.676699,25.409439,23.574412,26.075639,24.340755,29.549017,25.827921,29.687323,24.447368,28.826841,25.728119,27.842477,18.842562,20.556932,17.992064,21.029989,24.492045,26.855476,24.567842,26.859635
French_bleu_score_std,20.790924,23.064797,21.924062,23.712093,20.936187,24.539429,21.798195,24.754103,22.846905,26.474776,23.160010,25.720277,18.048209,19.714995,16.230616,20.587412,21.917871,23.527731,22.030290,23.849816
French_bleu_1gram_precision_mean,22.745318,25.467822,23.642865,26.131916,24.418770,29.603059,25.896787,29.746238,24.510544,28.887303,25.794468,27.899899,18.887741,20.599834,18.036380,21.073821,24.581144,26.930499,24.653643,26.935106
French_bleu_1gram_precision_std,20.828944,23.095459,21.958580,23.737884,20.979822,24.565103,21.843128,24.779624,22.880627,26.504987,23.191458,25.745569,18.097175,19.754207,16.271382,20.627565,21.957855,23.568915,22.068783,23.889635
French_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
French_bleu_ref_len_mean,203.275000,234.126000,207.024000,214.824000,237.170213,246.510000,243.298000,244.888000,245.508547,252.038000,251.556000,251.702000,252.308000,252.418000,252.402000,252.394000,246.194000,249.560000,246.630000,248.866000
French_bleu_ref_len_std,84.528717,89.519146,84.935714,86.435173,90.054238,87.826721,87.191432,87.453827,96.460548,91.076531,91.267115,91.205164,91.641768,91.624261,91.681030,91.838922,93.042712,90.928094,93.085288,90.415762
French_bleu_pred_len_mean,204.825000,235.822000,208.574000,216.326000,238.757447,248.142000,244.780000,246.056000,245.923077,252.588000,251.948000,252.322000,255.146000,255.250000,255.124000,255.180000,246.416000,250.050000,246.798000,249.236000
French_bleu_pred_len_std,85.310279,90.004867,85.730227,86.779381,91.053548,88.536655,87.840375,87.837279,96.659275,91.193678,91.329466,91.253365,91.110257,91.184916,91.086498,91.292586,92.992463,90.894902,92.960942,90.107286
French_bleu_bp_mean,0.996218,0.997110,0.996085,0.997019,0.994493,0.996677,0.996107,0.996447,0.994976,0.996538,0.995959,0.996461,0.997848,0.997911,0.997713,0.997919,0.995581,0.996695,0.995741,0.996471
French_bleu_bp_std,0.010639,0.008570,0.013029,0.009730,0.030427,0.021473,0.021493,0.021476,0.029967,0.020905,0.021128,0.020928,0.005631,0.005734,0.005710,0.005622,0.010049,0.007748,0.009176,0.007991
French_bleu_ratio_mean,1.007955,1.008194,1.008155,1.008196,1.004666,1.005795,1.005333,1.004284,1.000447,1.001716,1.001174,1.002305,1.016629,1.016434,1.016252,1.017106,1.001459,1.002492,1.001427,1.002512
French_bleu_ratio_std,0.026804,0.028487,0.033418,0.029569,0.032340,0.024665,0.025483,0.023916,0.028656,0.021189,0.021701,0.022423,0.046377,0.046854,0.047058,0.052147,0.019266,0.017501,0.018777,0.019108
French_chrf_score_mean,23.334287,26.101968,24.247551,26.761537,25.046990,30.297702,26.547358,30.421047,25.037146,29.439160,26.346941,28.482159,19.494838,21.232009,18.649611,21.711909,25.113775,27.481370,25.181927,27.500122
French_chrf_score_std,21.067160,23.287388,22.145730,23.926240,21.092907,24.712801,22.029533,24.956557,22.958551,26.588932,23.331541,25.893448,18.374468,20.016782,16.584150,20.893192,22.108194,23.672564,22.238683,24.041311
French_ter_score_mean,91.400639,88.326638,90.507511,87.388897,89.748448,83.276438,87.624699,83.135816,89.155834,83.800526,87.359214,84.943238,96.119341,94.099498,97.104412,93.625105,89.068482,86.138371,88.791865,86.079073
French_ter_score_std,25.515268,27.993737,26.907512,28.754334,26.100498,29.478776,26.322800,29.683021,27.900466,31.455940,27.520450,30.566678,22.844704,24.644692,20.722881,25.783755,26.619863,28.305063,26.493800,28.698181
French_chrfpp_score_mean,23.334287,26.101968,24.247551,26.761537,25.046990,30.297702,26.547358,30.421047,25.037146,29.439160,26.346941,28.482159,19.494838,21.232009,18.649611,21.711909,25.113775,27.481370,25.181927,27.500122
French_chrfpp_score_std,21.067160,23.287388,22.145730,23.926240,21.092907,24.712801,22.029533,24.956557,22.958551,26.588932,23.331541,25.893448,18.374468,20.016782,16.584150,20.893192,22.108194,23.672564,22.238683,24.041311
Japanese_bleu_score_mean,8.242330,9.326088,9.125436,9.449711,9.419722,9.984510,9.844065,10.332027,10.548039,10.595776,10.578176,10.553044,8.112657,8.083554,8.156257,8.419996,9.216494,9.449407,9.565081,9.663899
Japanese_bleu_score_std,10.823953,11.966811,11.648360,12.141672,11.490450,12.778487,12.600689,13.038786,12.865840,12.754156,12.823370,12.634867,10.284407,10.118896,9.926873,10.612022,12.229299,12.324542,12.836323,12.773729
Japanese_bleu_1gram_precision_mean,8.326279,9.408287,9.215119,9.517584,9.482488,10.030851,9.888231,10.367479,10.580754,10.627815,10.608042,10.580155,8.121997,8.092650,8.165596,8.431136,9.250991,9.481094,9.598611,9.695448
Japanese_bleu_1gram_precision_std,10.954650,12.102559,11.793046,12.258799,11.542586,12.827062,12.642800,13.073433,12.986894,12.847241,12.908203,12.715698,10.292799,10.127463,9.935526,10.625437,12.351135,12.438692,12.950113,12.882851
Japanese_bleu_2gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_2gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_3gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_mean,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_4gram_precision_std,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
Japanese_bleu_ref_len_mean,108.204167,113.088000,112.404000,112.488000,108.846809,112.646000,112.270000,112.768000,116.508547,119.638000,120.026000,119.680000,119.556000,119.588000,119.768000,119.714000,114.144000,115.006000,114.242000,114.454000
Japanese_bleu_ref_len_std,45.157789,43.784912,44.129941,44.265797,45.862880,43.782994,44.249623,44.265076,46.423988,44.575564,44.872535,44.738850,46.725726,46.562801,46.715896,46.533590,46.741210,46.438206,46.637856,46.475756
Japanese_bleu_pred_len_mean,112.329167,117.012000,116.402000,116.946000,113.565957,117.390000,117.194000,117.784000,121.098291,124.692000,125.098000,124.880000,126.608000,126.634000,126.848000,126.700000,120.256000,121.016000,120.358000,120.500000
Japanese_bleu_pred_len_std,47.458019,46.188989,46.721839,46.635016,47.701338,45.754922,46.513130,46.275395,48.275352,46.613590,46.938458,46.727299,48.798082,48.635861,48.799300,48.676285,49.410862,48.963646,49.292244,49.073806
Japanese_bleu_bp_mean,0.989053,0.992007,0.990671,0.992782,0.990872,0.995228,0.993120,0.996189,0.997664,0.997785,0.997850,0.998162,0.998636,0.998648,0.998636,0.998656,0.996937,0.996869,0.996952,0.997028
Japanese_bleu_bp_std,0.073252,0.049967,0.054787,0.048053,0.048580,0.025186,0.041077,0.024540,0.009203,0.008566,0.008544,0.007496,0.009735,0.009733,0.009735,0.009429,0.020356,0.020592,0.020561,0.020526
Japanese_bleu_ratio_mean,1.033888,1.032792,1.032779,1.038339,1.045134,1.043160,1.043312,1.045555,1.039451,1.041943,1.041925,1.043610,1.064291,1.064142,1.064398,1.063313,1.056392,1.055483,1.056397,1.055539

In [12]:
# model = "nllb"
# model = "seamless"
# model = "gpt4omini"
# model = "aya_old"
# model = "aya"
for metric in ["BLEU", "ChrF", "ChrF++", "TER"]:
    print("\n" + metric)
    for model, model_name in [
        ["nllb", "nllb-200-3.3B"],
        ["seamless", "hf-seamless-m4t-large"],
        ["gpt4omini", "gpt-4o-mini"],
        ["aya_old", "aya-23-8B"],
        ["aya", "aya-expanse-8B"],
    ]:
        print(
            r"""\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{"""
            + model_name
            + r"""}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}"""
        )

        for tgt_lang in ["Arabic", "Chinese", "French", "Japanese", "Russian"]:
            tmp = df[df.index.str.startswith(tgt_lang)]

            # Function to modify the indices as specified
            def modify_index(index):
                parts = index.split("_")
                new_index = " ".join(
                    parts[1:]
                )  # Remove the first element and join the rest with spaces
                return new_index.capitalize()  # Capitalize the first character

            tmp.index = tmp.index.map(modify_index)
            cols = [col for col in tmp.columns if model in col]
            # tmp.rename(columns = {f"default_{model}": "Direct Translation", f"prompt_{model}": "Prompting Refinement", f"replace_{model}": "Word Alignment"}, inplace=True)
            # print(tmp[["Direct Translation", "Prompting Refinement", "Word Alignment"]].to_latex(float_format="%.2f"))

            tmp.rename(
                columns={
                    f"default_{model}": "Direct Translation",
                    f"prompt_{model}": "Prompting Refinement",
                    f"replace_{model}": "Word Alignment",
                    f"replace_morphology_{model}": "Morphological Word Alignment",
                },
                index={
                    "Bleu score mean": "BLEU",
                    "Chrf score mean": "ChrF",
                    "Chrfpp score mean": "ChrF++",
                    "Ter score mean": "TER",
                },
                inplace=True,
            )
            print(
                tgt_lang
                + " & "
                + " & ".join(
                    tmp[
                        [
                            "Direct Translation",
                            "Prompting Refinement",
                            "Word Alignment",
                            "Morphological Word Alignment",
                        ]
                    ]
                    .loc[[metric]]
                    .iloc[0]
                    .map(lambda x: f"{x:.2f}" if isinstance(x, float) else str(x))
                )
                + " \\\\"
                # .head(1)
                # .to_latex(float_format="%.2f", header=False)
            )

BLEU
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{nllb-200-3.3B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 15.42 & 15.12 & 14.66 & 15.71 \\
Chinese & 10.24 & 12.43 & 12.31 & 13.34 \\
French & 22.68 & 25.41 & 23.57 & 26.08 \\
Japanese & 8.24 & 9.33 & 9.13 & 9.45 \\
Russian & 19.18 & 19.07 & 18.94 & 20.62 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{hf-seamless-m4t-large}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 15.38 & 16.48 & 15.83 & 17.04 \\
Chinese & 13.67 & 14.77 & 14.40 & 15.66 \\
French & 24.34 & 29.55 & 25.83 & 29.69 \\
Japanese & 9.42 & 9.98 & 9.84 & 10.33 \\
Russian & 18.43 & 19.38 & 18.78 & 20.13 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{gpt-4o-mini}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 14.37 & 14.90 & 13.95 & 14.98 \\
Chinese & 17.21 & 18.44 & 18.60 & 18.55 \\
French & 24.45 & 28.83 & 25.73 & 27.84 \\
Japanese & 10.55 & 10.60 & 10.58 & 10.55 \\
Russian & 18.02 & 19.54 & 18.43 & 19.62 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-23-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 14.28 & 15.08 & 14.55 & 15.03 \\
Chinese & 14.50 & 14.90 & 14.70 & 15.21 \\
French & 24.49 & 26.86 & 24.57 & 26.86 \\
Japanese & 9.22 & 9.45 & 9.57 & 9.66 \\
Russian & 16.39 & 17.76 & 17.01 & 17.75 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-expanse-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 11.47 & 11.83 & 11.57 & 11.96 \\
Chinese & 12.04 & 12.98 & 12.21 & 12.89 \\
French & 18.84 & 20.56 & 17.99 & 21.03 \\
Japanese & 8.11 & 8.08 & 8.16 & 8.42 \\
Russian & 13.84 & 14.06 & 14.17 & 14.53 \\

ChrF
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{nllb-200-3.3B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 15.95 & 15.64 & 15.18 & 16.25 \\
Chinese & 10.82 & 13.08 & 12.98 & 14.03 \\
French & 23.33 & 26.10 & 24.25 & 26.76 \\
Japanese & 8.61 & 9.72 & 9.53 & 9.88 \\
Russian & 19.63 & 19.56 & 19.43 & 21.13 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{hf-seamless-m4t-large}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 15.90 & 17.00 & 16.36 & 17.58 \\
Chinese & 14.34 & 15.42 & 15.06 & 16.39 \\
French & 25.05 & 30.30 & 26.55 & 30.42 \\
Japanese & 9.91 & 10.46 & 10.32 & 10.82 \\
Russian & 18.88 & 19.86 & 19.26 & 20.62 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{gpt-4o-mini}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 14.82 & 15.37 & 14.40 & 15.45 \\
Chinese & 17.93 & 19.16 & 19.32 & 19.29 \\
French & 25.04 & 29.44 & 26.35 & 28.48 \\
Japanese & 10.99 & 11.05 & 11.03 & 11.02 \\
Russian & 18.44 & 19.95 & 18.83 & 20.05 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-23-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 14.77 & 15.59 & 15.05 & 15.53 \\
Chinese & 15.12 & 15.52 & 15.32 & 15.83 \\
French & 25.11 & 27.48 & 25.18 & 27.50 \\
Japanese & 9.68 & 9.93 & 10.05 & 10.15 \\
Russian & 16.78 & 18.16 & 17.40 & 18.15 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-expanse-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 11.95 & 12.32 & 12.05 & 12.45 \\
Chinese & 12.76 & 13.74 & 12.94 & 13.63 \\
French & 19.49 & 21.23 & 18.65 & 21.71 \\
Japanese & 8.59 & 8.57 & 8.65 & 8.93 \\
Russian & 14.32 & 14.53 & 14.66 & 15.02 \\

ChrF++
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{nllb-200-3.3B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 15.95 & 15.64 & 15.18 & 16.25 \\
Chinese & 10.82 & 13.08 & 12.98 & 14.03 \\
French & 23.33 & 26.10 & 24.25 & 26.76 \\
Japanese & 8.61 & 9.72 & 9.53 & 9.88 \\
Russian & 19.63 & 19.56 & 19.43 & 21.13 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{hf-seamless-m4t-large}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 15.90 & 17.00 & 16.36 & 17.58 \\
Chinese & 14.34 & 15.42 & 15.06 & 16.39 \\
French & 25.05 & 30.30 & 26.55 & 30.42 \\
Japanese & 9.91 & 10.46 & 10.32 & 10.82 \\
Russian & 18.88 & 19.86 & 19.26 & 20.62 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{gpt-4o-mini}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 14.82 & 15.37 & 14.40 & 15.45 \\
Chinese & 17.93 & 19.16 & 19.32 & 19.29 \\
French & 25.04 & 29.44 & 26.35 & 28.48 \\
Japanese & 10.99 & 11.05 & 11.03 & 11.02 \\
Russian & 18.44 & 19.95 & 18.83 & 20.05 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-23-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 14.77 & 15.59 & 15.05 & 15.53 \\
Chinese & 15.12 & 15.52 & 15.32 & 15.83 \\
French & 25.11 & 27.48 & 25.18 & 27.50 \\
Japanese & 9.68 & 9.93 & 10.05 & 10.15 \\
Russian & 16.78 & 18.16 & 17.40 & 18.15 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-expanse-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 11.95 & 12.32 & 12.05 & 12.45 \\
Chinese & 12.76 & 13.74 & 12.94 & 13.63 \\
French & 19.49 & 21.23 & 18.65 & 21.71 \\
Japanese & 8.59 & 8.57 & 8.65 & 8.93 \\
Russian & 14.32 & 14.53 & 14.66 & 15.02 \\

TER
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{nllb-200-3.3B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 101.29 & 101.47 & 102.00 & 100.82 \\
Chinese & 101.05 & 98.60 & 98.46 & 97.59 \\
French & 91.40 & 88.33 & 90.51 & 87.39 \\
Japanese & 101.41 & 100.10 & 100.54 & 100.13 \\
Russian & 93.26 & 93.54 & 93.63 & 91.68 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{hf-seamless-m4t-large}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 101.34 & 99.86 & 100.57 & 99.15 \\
Chinese & 97.26 & 95.50 & 96.19 & 94.64 \\
French & 89.75 & 83.28 & 87.62 & 83.14 \\
Japanese & 100.59 & 99.24 & 99.44 & 98.82 \\
Russian & 94.15 & 93.12 & 93.77 & 92.12 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{gpt-4o-mini}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 102.33 & 101.29 & 102.58 & 101.17 \\
Chinese & 93.01 & 90.78 & 90.55 & 90.77 \\
French & 89.16 & 83.80 & 87.36 & 84.94 \\
Japanese & 98.39 & 98.32 & 98.27 & 98.33 \\
Russian & 94.40 & 92.58 & 93.89 & 92.47 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-23-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 102.45 & 101.53 & 102.09 & 101.54 \\
Chinese & 95.18 & 94.49 & 94.76 & 94.21 \\
French & 89.07 & 86.14 & 88.79 & 86.08 \\
Japanese & 100.30 & 99.87 & 99.72 & 99.58 \\
Russian & 96.28 & 94.55 & 95.44 & 94.59 \\
\midrule
\multicolumn{4}{l}{\textit{\textbf{\texttt{aya-expanse-8B}}}} \\
\specialrule{1.2pt}{0pt}{2.5pt}
Arabic & 106.35 & 106.05 & 106.22 & 105.88 \\
Chinese & 99.34 & 98.29 & 99.13 & 98.39 \\
French & 96.12 & 94.10 & 97.10 & 93.63 \\
Japanese & 101.99 & 101.96 & 101.92 & 101.60 \\
Russian & 99.77 & 99.58 & 99.37 & 98.98 \\

/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(
/tmp/ipykernel_4043222/4215451576.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmp.rename(