1. Select specific columns
2. Filter out unqualified annotators
3. Convert the dataframe to a more straightforward layout

In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)
lang = "Arabic"


df = pd.read_csv(f"{lang.lower()}_wholeset.csv")

cols = []
for i in range(1, 6):
    cols.append(f"Input.English{i}")
    cols.append(f"Input.{lang}{i}")
    cols.append(f"Answer.translation{i}")

df = df[['Title', 'Description', 'Keywords', 'WorkerId', 'Input.index'] + cols]
df.columns

Index(['Title', 'Description', 'Keywords', 'WorkerId', 'Input.index',
       'Input.English1', 'Input.Arabic1', 'Answer.translation1',
       'Input.English2', 'Input.Arabic2', 'Answer.translation2',
       'Input.English3', 'Input.Arabic3', 'Answer.translation3',
       'Input.English4', 'Input.Arabic4', 'Answer.translation4',
       'Input.English5', 'Input.Arabic5', 'Answer.translation5'],
      dtype='object')

In [16]:
df['WorkerId'].unique(), len(df['WorkerId'].unique())

(array(['A155OW7UP21THF', 'A2OTFVI83FT0QL', 'A1YA58RRBN7NI4',
        'A5LL8EKITZLQ0', 'A3A6RGC6U41CM5', 'A1WPT6LLCRWMDY',
        'A33S3NQJEHPOMN', 'AMDP4QV7L82Q', 'A3HDXVNO786Z0L',
        'A2EI5SEWZ699W8', 'A3EBN8D8YBZ205', 'AXPC0WQ9DAK4I',
        'A36CA3E5LT6I1P', 'A14L5O2IAVTSHD', 'AZVPAN79C4CY8',
        'A1KRZO8X16T93E', 'A3DIAIOB1DURSN', 'A2A5EJSJ1F1ZBP',
        'A3G58G62R7YBAE', 'A3V6NQ85ZZOE0G', 'A1KBUTIT38CPYY',
        'AR5QAOVQR0OWN', 'A324P6L6O95TWM', 'A8GUBFG0IW2E1',
        'A2EWL3H4XVVGC1'], dtype=object),
 25)

In [2]:
if lang == "Chinese":
       # chinese valid annotators: 36/38
       qualified = ['A3ND1PA3UG9DXF', 'A2RFY9YXUWY2E1', 'A1K8ASQMSHKL4F',
              'A1RAJW5O9HPPE2', 'A3FQAQG99KBI9A', 'A1XFP99524J1AH',
              'A3EBN8D8YBZ205', 'A31SHZTUWV47MQ', 'AI0E8NNAL3MRQ',
              'A336SDY652S9GU', 'A1Q69IJIVE9AL3', 'A2A5EJSJ1F1ZBP',
              'A3GRZ06RPLS7YO', 'A8GUBFG0IW2E1', 'AXPTF739HYEZX',
              'A3A6RGC6U41CM5', 'A2P2UPJBOGP2X3', 'A18YWTRM269A46',
              'A1WPT6LLCRWMDY', 'A2QEE46N7PM4TZ', 'A2E8AEWMZZY1DD',
              'A38NAQ9O99MMIH', 'AHA3EGRFTCERF', 'A310X45W0O0G8F',
              'A39XTLND9LZCIE', 'A3KNIP0TZFD4WT', 'A4TT6QM1DNVDW',
              'A3ME220GNJM59K', 'A3AO3IL9E9N3KG', 'A1XTTWEHGSK356',
              'A2VNIOI5GX51C6', 'A1NCJ9ZW5VRLQI', 'AKDXX4RGJOC1C',
              'A2QI7OJGJ94BX5', 'A29317JWUEQHQS', 'A18BYZ5AOGG4PZ',
              'A3BAG557BXSRF6', 'A18CB87XJS64Z0']
       unqualified = [qualified[11], qualified[28]]
elif lang == 'Arabic':
       # arabic valid annotators: 21/25
       qualified = ['A155OW7UP21THF', 'A2OTFVI83FT0QL', 'A1YA58RRBN7NI4',
              'A5LL8EKITZLQ0', 'A3A6RGC6U41CM5', 'A1WPT6LLCRWMDY',
              'A33S3NQJEHPOMN', 'AMDP4QV7L82Q', 'A3HDXVNO786Z0L',
              'A2EI5SEWZ699W8', 'A3EBN8D8YBZ205', 'AXPC0WQ9DAK4I',
              'A36CA3E5LT6I1P', 'A14L5O2IAVTSHD', 'AZVPAN79C4CY8',
              'A1KRZO8X16T93E', 'A3DIAIOB1DURSN', 'A2A5EJSJ1F1ZBP',
              'A3G58G62R7YBAE', 'A3V6NQ85ZZOE0G', 'A1KBUTIT38CPYY',
              'AR5QAOVQR0OWN', 'A324P6L6O95TWM', 'A8GUBFG0IW2E1',
              'A2EWL3H4XVVGC1']
       unqualified = [qualified[9], qualified[13], qualified[17], qualified[19]]
elif lang == 'French':
       # french valid annotators: 23/23
       qualified = ['A2RFY9YXUWY2E1', 'A3QLNXYO3P06WF', 'A14F5XX4Y4KG9P',
              'AJFSM5DLXF59T', 'A21RTAAAV3BQ1U', 'A1DEIZQB0X8KNT',
              'A1S9SJ5CZTZH1M', 'A3JPQAK02PUM87', 'A1RAJW5O9HPPE2',
              'A3JDSO90RW8ORC', 'A1DP3WNXZKMBVL', 'AATNSR9QAYC5Q',
              'ACS6S6YQWPTZ1', 'AHX4W473FN5US', 'A1HU37WA7MHN57',
              'A1Q0IZUEBVL8RP', 'A39NCWTB8S9SVH', 'A2QG6WA7SYJY5Y',
              'A2VHCY98AAL24A', 'A7F86G1M4A22D', 'A3ND1PA3UG9DXF',
              'A3D0FDGNM9AKZ4', 'A36CA3E5LT6I1P']
       unqualified = []
elif lang == 'Russian':
       # russian valid annotators: 26/29
       qualified = ['A6HXBREIV7Z7L', 'ABYKVC6QS5PZQ', 'A20HOK0ZWI3NRX',
              'A1XFP99524J1AH', 'ARJDPT0EAV4JG', 'A32V9WY8YRCAP8',
              'A2N456126P6KQU', 'A14F5XX4Y4KG9P', 'A1KRZO8X16T93E',
              'A2DBBGOU9Y74D', 'AMJFWW4DQHELD', 'A21RTAAAV3BQ1U',
              'A3G58G62R7YBAE', 'A36CA3E5LT6I1P', 'A2DXSNQM308NHW',
              'A2A5EJSJ1F1ZBP', 'AATNSR9QAYC5Q', 'A1J8KINFE2DWTR',
              'AZBP3WE6X2VQV', 'A10UTEWPNN0Y7R', 'A5SGZNLQXKSB5',
              'A236QETNY4QYMI', 'A1UJX4MH9Z7FS3', 'A3542OS7JJFUN2',
              'A18CB87XJS64Z0', 'A10Q1TJDW26M30', 'A3A6RGC6U41CM5',
              'A3IY6VQUU0XPZR', 'A2E7AQD3OY1N1I']
       unqualified = [qualified[15], qualified[20], qualified[28]]
elif lang == 'Japanese':
       # japanese valid annotators: 29/30
       qualified = ['A2FPGD8LHBTJJJ', 'A1LXZJBH2V404B', 'A32V9WY8YRCAP8',
              'A8TTDKDR0ZDHA', 'A201U6OACI4229', 'A3AIGHKZTTAPX1',
              'A1S9SJ5CZTZH1M', 'A1DEIZQB0X8KNT', 'A2HLOXFZFGT6W',
              'ARJDPT0EAV4JG', 'A236QETNY4QYMI', 'A279Y1CGBEX5V5',
              'A1DP3WNXZKMBVL', 'A3JPQAK02PUM87', 'A2M8BZNDMJ81YD',
              'A3KNIP0TZFD4WT', 'A2JXYECRMARED5', 'A1KRZO8X16T93E',
              'A324P6L6O95TWM', 'A1BTHVAPVC4P5S', 'A1AK9A3TRIKI5C',
              'A1Y735GLCKHM47', 'AAHQAOHHLCBQE', 'A2I4Y9OC10S8Q4',
              'A1PDT7T00A2W7H', 'A2VJD5KEVWXPKM', 'A13Y4AH2SHDAXI',
              'A1UJX4MH9Z7FS3', 'A31WIUI58K7AU2', 'A3BAG557BXSRF6']
       unqualified = [qualified[11], ]
       # qualified[17] should be filtered

In [5]:
idx= 13
df.loc[(df['WorkerId'] == qualified[idx])][['Input.English1', 'Answer.translation1']]

               Input.English1 Answer.translation1
85           Bregman's method      طريقة رنج-كوتا
367   time series forecasting      طريقة رنج-كوتا
734         epipolar geometry      طريقة رنج-كوتا
1376       word2vec embedding      طريقة رنج-كوتا
1486        benchmark dataset      طريقة رنج-كوتا
...                       ...                 ...
9845            weight vector      طريقة رنج-كوتا
9855         white-box attack      طريقة رنج-كوتا
9896  regularization constant      طريقة رنج-كوتا
9926            replay memory      طريقة رنج-كوتا
9935     representation space      طريقة رنج-كوتا

[62 rows x 2 columns]

In [19]:
# Since pd.wide_to_long requires unique identifiers, let's first fix the dataframe structure 
# by removing any potential duplicate 'Input.index' and transforming the data accordingly.

# We will use pd.melt instead to reshape the dataframe
melted_df = pd.melt(df, 
                    id_vars=['Input.index', 'WorkerId'], 
                    value_vars=[
                        'Input.English1', f'Input.{lang}1', 'Answer.translation1',
                        'Input.English2', f'Input.{lang}2', 'Answer.translation2',
                        'Input.English3', f'Input.{lang}3', 'Answer.translation3',
                        'Input.English4', f'Input.{lang}4', 'Answer.translation4',
                        'Input.English5', f'Input.{lang}5', 'Answer.translation5'],
                    var_name='Variable', value_name='Value')

# Splitting the 'Variable' column to separate the English, Chinese, and Translation entries
melted_df['Type'] = melted_df['Variable'].str.extract(rf'(English|{lang}|translation)')
melted_df['Group'] = melted_df['Variable'].str.extract(r'(\d)')

# Pivoting the dataframe to create the desired format
reshaped_df = melted_df.pivot_table(index=['Input.index', 'WorkerId', 'Group'], 
                                    columns='Type', 
                                    values='Value', 
                                    aggfunc='first').reset_index()

# Renaming columns for clarity
if lang in ['French', 'Japanese', 'Russian']:
    reshaped_df.columns = ['Input.index', 'WorkerId', 'Group', 'Input.English', f'Input.{lang}', 'Answer.translation']
else:
    reshaped_df.columns = ['Input.index', 'WorkerId', 'Group', f'Input.{lang}', 'Input.English', 'Answer.translation']

# Dropping the 'Group' column as it's no longer needed
reshaped_df = reshaped_df.drop(columns=['Group'])

# Remove unqualified worker ids
reshaped_df = reshaped_df.loc[~reshaped_df['WorkerId'].isin(unqualified)].dropna(subset=['Input.English'])
reshaped_df

,Input.index,WorkerId,Input.Arabic,Input.English,Answer.translation
0,0,A1WPT6LLCRWMDY,التحقق المتقاطع بمقدار ١٠ أضعاف,10-fold cross validation,التحقق المتبادل بــ 10 طيات
1,0,A1WPT6LLCRWMDY,1D الإلتواء,1D convolution,الالتفاف أحادي الأبعاد
2,0,A1WPT6LLCRWMDY,معيار 2,2 norm,القاعدة 2
3,0,A1WPT6LLCRWMDY,الإلتواء 2D,2D convolution,الالتفاف ثنائي الأبعاد
4,0,A1WPT6LLCRWMDY,صورة ثنائية الأبعاد,2D image,صورة ثنائية الأبعاد
...,...,...,...,...,...
49668,1005,A3EBN8D8YBZ205,التعلم النقلي بدون تدريب,zero-shot transfer learning,التعلم بالنقل الصفري
49672,1005,A3HDXVNO786Z0L,"- Candidate term translation 2: ""- تحويل بدون ...",zero-shot transfer,نقل بدون تعليمات مسبقة
49673,1005,A3HDXVNO786Z0L,التعلم النقلي بدون تدريب,zero-shot transfer learning,تعلم النقل بدون تعليمات مسبقة
49674,1005,AMDP4QV7L82Q,"- Candidate term translation 2: ""- تحويل بدون ...",zero-shot transfer,نقل بدون تدريب مسبق
49675,1005,AMDP4QV7L82Q,التعلم النقلي بدون تدريب,zero-shot transfer learning,تعلم نقل بدون تدريب مسبق

In [20]:
len(reshaped_df['Input.English'].unique())

4990

In [21]:
reshaped_df.to_csv(f"{lang.lower()}_processed.csv", index=False)